const Laboratories = [
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "     براي 25 بيماري Metabolic Disorders Screening Test (By TMS Method)-آزمايش هاي غربالگري بيماري هاي متابوليک Test Metabolic Disorders Screening (by TMS Method) براي 25 بيماري ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "801260-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "  Alpha Heavy Chain - آزمايش تجسس زنجيره سنگين آلفا ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "802950-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "  tyr/Phe in ser-اندازه‌گيري کمّي فنيل آلانين يا تيروزين به روش شيميايي در سرم/پلاسما ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "801000-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " Anti-Pneumonia-آنتي بادي پنومونيا براي هر کلاس",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "803515-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " CCIE-آزمايش Current Immuno Electrophoresis) CCIE Counter) ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800770-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Check Mutation more than 50 exogen bay  determan squense-بررسي بيش از 50 اگزون با روش تعيين توالي ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "810282-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Check Panel Mutation1-20 gens by NGS-بررسي 1 تا 20 ژن به صورت يک پانل توسط روش هاي NGS (اين کد با ساير کدها قابل گزارش و محاسبه نمي باشد) (در صورت ارسال نمونه به خارج از کشور صرفاً مشروط به رعايت استانداردهاي ابلاغي وزارت بهداشت درمان و اموزش پزشکي، 90 درصد جزء فني و 5 درصد جزء حرفه اي قابل محاسبه و پرداخت است.) (قيمت توليد داده خام به عنوان بخشي از جزء فني براساس اعلام رسمي وزارت بهداشت درمان و آموزش پزشکي به صورت دوره اي، قابل محاسبه و پرداخت مي باشد.)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "002",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "810300-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Copper (ur/Random)-اندازه‌گيري کمّي مس ادرار روش اسپكتروفتومتري ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "019123-919",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Copper (ur24 hrs)-اندازه‌گيري کمّي مس ادرار 24 ساعته روش اسپكتروفتومتري ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "019123-918",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Cortisol  9h after 1mg Dexametazon-آزمايش کورتيزول9ساعت دقيقه بعد از تزريق دگزا متازون  سرم/پلاسما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "002145-104",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Cortisol 24h after 1mg Dexametazon-آزمايش کورتيزول24ساعت بعد از تزريق دگزا متازون  سرم/پلاسما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "002145-105",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " Dopamine Random in Serum or Plasma-اندازه‌گيري کمّي دوپامين در سرم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "057772-622",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " E- Test -آزمايش E- Test براي هر آنتي بيوتيك ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "804170-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " FFP-پلاسما FFP ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "802656-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " FLT3 بررسي ترانسلوکاسيون در سرطان هاي خون ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "002",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "810062-017",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " HLA A,B, C Typing class I  -آزمايش HLA Typing كلاس I ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "802580-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " HLA A,B, C Typing class II   -آزمايش HLA Typing كلاس II ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "802585-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " MDR1 بررسي ترانسلوکاسيون در سرطان هاي خون ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "002",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "810062-016",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " Pb/ur-اندازه‌گيري کمّي سرب ادرار روش اسپكتروفتومتري ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "019123-915",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " Red Blood Cell poor WBC-گلبول قرمز با حذف لكوسيت ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "802660-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " Xylocaine Test-آزمايش Xylocaine ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "803680-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " croThin laye-آزمايش كروماتوگرافي لايه نازک (Thin layer) ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800795-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " croThin laye/ mtabu dis blood-آزمايش كروماتوگرافي لايه نازک (Thin layer) متابوليت مرتبط با بيماري هاي متابوليک در خون ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800798-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " croThin laye/ mtabu dis blood-آزمايش كروماتوگرافي لايه نازک (Thin layer) مواد روان گردان، مخدر و داروها و متابوليت آن ها در ادرار ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800797-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " croThin laye/blood-آزمايش كروماتوگرافي لايه نازک (Thin layer) مواد روان گردان، مخدر و داروها و متابوليت آن ها در خون ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800796-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " croThin laye/ur fiu-آزمايش كروماتوگرافي لايه نازک (Thin layer) مواد روان گردان، مخدر و داروها و متابوليت آن ها در ادرار و مايعات بدن ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800799-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " determan Mutation Exogen 26-50-بررسي 26 تا 50 اگزون ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "810268-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " the final status of the fetus other disease-تعيين وضعيت نهايي جنين براي ساير بيماري ها (چند قلو)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "806580-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " اندازه‌گيري کمّي (LH)  لوتين هورمون خون ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "010501-500",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " اندازه‌گيري کمّي آلدسترون در سرم/پلاسما  (Upright)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "001763-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " اندازه‌گيري کمّي انسولين 1ساعته) در سرم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "020448-701",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " اندازه‌گيري کمّي بتا-2- ميکروگلوبولين ادرار ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "001952-101",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "( Sickle Cell Anemia stage- 2  finale statuse of the fetuse-آنمي داسي شکل ( Sickle Cell Anemia ) / مرحله دوم تعيين وضعيت جنين(چند قلو)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "806525-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "(Foam Stability Test/Amniotic   -آزمايش ثبات كف (Foam Stability Test) در مايع آمنيوتيك ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "800905-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "(IHC)- (IHC)ايمونوهيستوشيمي (شامل ايمونوپراكسيد از بافتي)، ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "001",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "807135-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      ",,DRB1L,HA/PCR -تعيين پرايمرها با استفاده از PCR براي تشخيص آلل‌هاي ,,DRB1,HLA هر يک به تنهايي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "805108-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      ",DQAL,HLA/PCR -تعيين پرايمرها با استفاده از PCR براي تشخيص آلل هاي ,DQAL,HLA هر يک به تنهايي گيرنده",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "805107-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      ",DRB2,,HA/PCR -تعيين پرايمرها با استفاده از PCR براي تشخيص آلل‌هاي ,DRB2,,HLA هر يک به تنهايي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "805108-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Cerebrospinal Fluid Panel-آزمايش روتين : شامل گلوکز، پروتئين و تجسس ميکروسکوپي و شمارش سلولها در مايع مغزي نخاع",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "804420-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "-Cotinine in Urine-تجسس و تشخيص مواد مخدرکوتينين در ادارار",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "003826-505",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-HCV  DNA PCR-استفاده از RT/PCR کمي براي تعيين بار ويروس هپاتيت C ",
    srvName2: null,
    srvBimSw: null,
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "003",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "805082-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Metanephrine Free [Mass/volume] in Serum or Plasma-اندازه‌گيري کمّي متانفرين آزاد در سرم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "021019-503",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Metanephrines [Mass/time] in 24 hour Urine-اندازه‌گيري کمّي متانفرين در ادرار 24ساعته  ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "021019-504",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Normetanephrine Free [Mass/volume] in Serum or Plasma-اندازه‌گيري کمّي متانفرين، نورمتانفرين آزاد در سرم ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "021019-507",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Normetanephrine [Mass/volume] in Serum or Plasma-اندازه‌گيري کمّي نورمتانفرين آزاد در سرم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "021019-506",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Other Body Fluids Panel-آزمايش روتين  شامل گلوکز، پروتئين و تجسس ميکروسکوپي و شمارش سلولها در ساير مايعات مايع بدن ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "804420-500",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Pericardial Fluid Panel-آزمايش روتين : شامل گلوکز، پروتئين و تجسس ميکروسکوپي و شمارش سلولها در مايع پري کارديال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "804420-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Peritoneal Fluid Panel-آزمايش روتين : شامل گلوکز، پروتئين و تجسس ميکروسکوپي و شمارش سلولها در مايع پريتونيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "804420-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-Pleural Fluid Panel-آزمايش روتين  شامل گلوکز، پروتئين و تجسس ميکروسکوپي و شمارش سلولها در مايع پلورال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "804420-400",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "1003713008-دريچه مصنوعي قلب به عنوان نمونه (نمونه) ارسال شد",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "001",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "807243-007",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "1003714002-نمونه از دريچه مصنوعي قلب (نمونه)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "001",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "807243-008",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "02",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "1007-4-Direct Coombs -آزمايش كومبس مستقيم ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: {
      parGrpCode: "004",
      parGrpDesc: null,
      parGrpRem: null,
      status: null,
      statusStDate: null,
    },
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "001007-400",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
];

export default Laboratories;
