const Imaging = [
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " سي تي اسکن اسپيرال حنجره يک جهت با و بدون تزريق",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702805-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24545-6-سي تي اسکن آئورت سينه اي با کنتراست وريدي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024545-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24585-2-بيوپسي استريوتاکتيک سر با کنتراست وريدي تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024585-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24623-1-بلوك عصبي سلياك پلكسوس تحت گايد سي تي اسكن",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024623-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24628-0,116152004-سي تي اسکن قفسه سينه با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702820-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24628-0-سي تي اسکن قفسه سينه با کنتراست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702245-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24697-5-سي تي اسکن استخوان هاي صورت با کنتراست- يک جهت - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024697-502",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24726-2,116152004-سي تي اسکن  مغز با و بدون کنتراست -اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024726-202",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24726-2,81654009,24422004-سي تي اسکن مغز با و بدون کنتراست کرونال و اگزيال ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024726-201",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24726-2-سي تي اسکن مغز با و بدون تزريق",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024726-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24727-0,116152004-سي تي اسکن  مغز با کنتراست -اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024727-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24727-0,81654009,24422004-سي تي اسکن مغز؛ کرونال و آگزيال (با تزريق)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024727-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24727-0-سي تي اسکن مغز با کنتراست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024727-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24734-6,81654009,24422004-سيسترنوگرافي مغز در دو جهت با تزريق اينتراتکال-کرونال وآگزيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024734-601",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24734-6-سيسترنوگرافي مغز در يک جهت با تزريق اينتراتکال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024734-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24812-0-بيوپسي کبد تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024812-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24815-3,116152004-سي تي اسکن کبد با کنتراست  - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702915-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24815-3-سي تي اسکن کبد با کنتراست ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024815-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24837-7-آسپيراسيون مايع گردن تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024837-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24849-2,116152004-سي تي اسکن  اربيت با و بدون کنتراست دوجهت- هر دوچشم - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024849-201",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24849-2,81654009,24422004-سي تي اسکن اربيت با و بدون کنتراست دوجهت- هر دوچشم-کرونال وآگزيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702130-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24849-2-سي تي اسکن اربيت با و بدون کنتراست يک جهت- هر دوچشم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024849-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24850-0,116152004-سي تي اسکن  اربيت دوجهت با کنتراست- هر دوچشم - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024850-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24850-0,81654009,24422004-سي تي اسکن  اربيت با کنتراست دوجهت- هر دوچشم-کرونال وآگزيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702125-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24850-0-سي تي اسکن اربيت با  کنتراست يک جهت- هر دوچشم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024850-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24856-7-آسپيراسيون مايع پانکراس تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024856-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24857-5,116152004-سي تي اسکن پانکراس باتزريق- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024857-500",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24858-3,116152004-سي تي اسکن پانکراس با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024858-301",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24858-3-سي تي اسکن پانکراس با کنتراست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024858-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24866-6,116152004-سي تي اسكن لگن با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024866-601",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24866-6-سي تي اسكن لگن با کنتراست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024866-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24877-3,81654009,24422004-سي تي اسكن استخوان تمپورال ( پتروس)يا گوش داخلي - دو جهت -کرونال وآگزيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024877-301",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24877-3-سي تي اسكن استخوان تمپورال ( پتروس)يا گوش داخلي يك جهت با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024877-400",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24878-1,116152004-سي تي اسكن استخوان تمپورال ( پتروس)يا گوش داخلي يك جهت با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024878-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24933-4,116152004-سي تي اسكن فقرات گردني با کنتراست - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024933-400",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24933-4-سي تي اسکن مهره هاي ناحيه گردني- با تزريق وريدي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702375-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24964-9,116152004-سي تي اسكن فقرات كمري با کنتراست وريدي- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024964-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24964-9-سي تي اسکن مهره هاي ناحيه لومبار- با تزريق وريدي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702365-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24979-7,116152004-سي تي اسكن فقرات سينه اي با کنتراست وريدي- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024979-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24979-7-سي تي اسکن مهره هاي ناحيه توراسيک- با تزريق وريدي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702370-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24986-2-بيوپسي از ستون فقرات تحت گايد سي تي اسكن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024986-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24987-0-سي تي اسکن ستون فقرات- با تزريق وريدي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702380-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "25052-2-سي تي اسکن مقاطع کرونال -ساجيتال يا ابليک",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702030-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "29252-4,116152004-سي تي اسکن ريه بدون کنتراست - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702815-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "29252-4-سي تي اسکن ريه بدون کنتراست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702240-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30583-9,116152004,81654009,24422004-سي تي اسکن اسپيرال گوش داخلي با تزريق-آگزيلار",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702735-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30583-9,116152004-سي تي اسكن گوش داخلي يك جهت با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030583-901",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30583-9,81654009,24422004-سي تي اسکن گوش داخلي با تزريق دوجهت-کرونال وآگزيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702160-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30583-9-سي تي اسكن گوش داخلي يك جهت با کنتراست ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030583-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30584-7,116152004-سي تي اسكن گوش داخلي يك جهت بدون کنتراست - اسپيرال ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030584-702",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30584-7-سي تي اسكن گوش داخلي يك جهت بدون کنتراست ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030584-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30586-2,116152004-سي تي اسکن گردن با و بدون کنتراست - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030586-201",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30586-2-سي تي اسکن گردن با و بدون کنتراست ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030586-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30587-0,116152004-سي تي اسکن  اربيت بدون کنتراست دوجهت- هر دوچشم - اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030587-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30587-0,81654009,24422004-سي تي اسکن اربيت بدون کنتراست دوجهت- هر دوچشم-کرونال وآگزيال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702120-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30589-6,116152004-سي تي اسكن استخوان تمپورال ( پتروس)يا گوش داخلي  دو جهت بدون کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702725-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30589-6-سي تي اسكن استخوان تمپورال ( پتروس) يا گوش داخلي يك جهت بدون کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030589-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30590-4,116152004-سي تي اسكن هيپوفيز و سلا توريكا با کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030590-401",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30591-2,116152004-سي تي اسكن هيپوفيز و سلا توريكا بدون کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030591-201",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30592-0,116152004-سي تي اسكن فقرات گردني بدون تزريق کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030592-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30592-0-سي تي اسکن مهره هاي ناحيه گردني- بدون تزريق",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702355-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30597-9,116152004-سي تي اسكن فقرات پشتي بدون تزريق وريدي- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030597-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30597-9-سي تي اسکن مهره هاي ناحيه توراسيک - بدون تزريق",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702350-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "30598-7,116152004-سي تي اسکن  قفسه سينه با و بدون کنتراست- اسپيرال",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702825-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30598-7-سي تي اسکن ريه با و بدون کنتراست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "702250-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30603-5-آسپيراسيون سوزني (FNA) کبد تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030603-500",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30604-3-بيوپسي پانکراس تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030604-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30605-0-آسپيراسيون سوزني (FNA)پانکراس تحت گايد سي تي اسکن",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030605-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30606-8-آسپراسيون سوزني لگن (FNA) تحت گايد سي تي اسكن",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030606-800",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30607-6-بيوپسي كليه ها تحت گايد سي تي اسكن",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030607-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "05",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "30608-4-بيوپسي  آسپيراسيون سوزني (FNA) كليه تحت گايد سي تي اسكن",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "030608-400",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
];
export default Imaging;
