const Radiology = [
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "037790-3-راديوگرافي اسکاپولاي راست نماي (Y) ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "037790-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24564-7-راديوگرافي ساده شکم نماي (AP) ايستاده - پرتابل",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024564-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24575-3-راديوگرافي کلانژيوگرافي از راه پوست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700300-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24637-1-راديوگرافي قفسه صدري نماي LEFT Ap- LATERAL DECUBITUS(يک فيلم )",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024637-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24639-7-راديوگرافي قفسه سينه ايستاده نماي (Left lateral )",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024639-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24657-9-توموگرافي قفسه سينه",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024657-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24666-0-راديوگرافي باريم آنما دوبل کنتراست حداقل 6کليشه",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700285-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24668-6-راديوگرافي ترانزيت کولون Colon Transit Time (CTT)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700395-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24695-9-راديو گرافي استخوانهاي صورت -  دو نما ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024695-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24712-2-راديوگرافي كيسه صفرا با كنتراست خوراكي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024712-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24724-7-راديوگرافي مچ دست جهت تعيين سن استخواني دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024724-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24767-6-توموگرافي گوش داخلي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024767-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24784-1-توموگرافي كليه ها- با و بدون كنتراست وريدي- دوطرفه",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024784-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24788-2-راديوگرافي كليه ها با كنتراست وريدي- دوطرفه",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024788-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24789-0-توموگرافي كليه ها- دوطرفه",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024789-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24795-7-راديوگرافي شكم نماي ايستاده و خوابيده- پرتابل",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024795-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24798-1-راديوگرافي شكم نماي ايستاده و خوابيده",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024798-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24799-9-راديوگرافي شكم نماي (AP) ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024799-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24828-6-توموگرافي پانوراميك OPG",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024828-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24829-4,399348003-راديوگرافي منديبل دونما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "036711-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24829-4,49370004-راديوگرافي منديبل نيم رخ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "036754-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24834-4-راديوگرافي استخوان بيني دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024834-400",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24843-5-راديوگرافي گردن نماي (Lateral)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700110-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24854-2-راديوگرافي اربيت دو طرفه دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024854-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24919-3-راديوگرافي جمجمه نماي (AP ) و (Lateral)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024919-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24921-9-راديوگرافي جمجمه نماي (Waters)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024921-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24924-3-راديوگرافي ترانزيت روده هاي کوچک",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700275-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24942-5-راديوگرافي ستون فقرات گردني نماي (AP) و (Lateral)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024942-500",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24948-2-راديوگرافي مهره دوم گردني وزائده ادنتوئيد نماي (AP)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024948-200",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24969-8,255536004-راديوگرافي ستون فقرات کمري نماي (Lateral)-اکستنسيون",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024969-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "24969-8,261081002-راديوگرافي ستون فقرات کمري نماي (Lateralفلکسيون",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024969-800",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24970-6-راديوگرافي ستون فقرات کمري نماي (AP) و (Lateral)",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "036670-800",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24983-9-راديوگرافي ستون فقرات پشتي - دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024983-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "24994-6-گرافي استرنوم",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "024994-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "25020-9-راديوگرافي يورتروسيستوگرافي با ماده حاجب رتروگراد",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700360-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "25034-0,24028007-آرتروگرافي مچ دست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700560-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "25034-0,7771000-آرتروگرافي مچ دست",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "700560-002",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "25074-6-راديوگرافي قوس زيگوماتيک - دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "025074-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26128-9-راديو گرافي کف پاي چپ دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026128-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26143-8-راديوگرافي كانال اپتيك چپ دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026143-800",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26144-6-راديوگرافي كانال اپتيك راست دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026144-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26161-0-راديوگرافي انگشت اول دست چپ- دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "036656-700",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26162-8-راديوگرافي انگشت اول دست راست - دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "025006-900",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26173-5-راديوگرافي قوس زيگوماتيک چپ- دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026173-500",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26174-3-راديوگرافي قوس زيگوماتيک راست- دو نما",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026174-300",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26175-0-ماموگرافي غربالگري پستان دوطرفه ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026175-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26176-8-ماموگرافي غربالگري پستان چپ ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026176-800",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26177-6-ماموگرافي غربالگري پستان راست ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026177-600",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26316-0-لوکاليزاسيون توده پستان چپ تحت هدايت ماموگرافي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026316-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "03",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "26317-8-لوکاليزه کردن توده پستاني  راست تحت هدايت ماموگرافي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "026317-800",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
];
export default Radiology;
