const data2 = [
  {
    drugInstId: 60,
    drugInstCode: "229797004",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "يک بار در روز",
  },
  {
    drugInstId: 61,
    drugInstCode: "61",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "دو بار در روز",
  },
  {
    drugInstId: 62,
    drugInstCode: "62",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "سه بار در روز",
  },
  {
    drugInstId: 63,
    drugInstCode: "63",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "چهار بار در روز",
  },
  {
    drugInstId: 64,
    drugInstCode: "64",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر 4 ساعت",
  },
  {
    drugInstId: 65,
    drugInstCode: "65",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر 6 ساعت",
  },
  {
    drugInstId: 66,
    drugInstCode: "66",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر 8 ساعت",
  },
  {
    drugInstId: 67,
    drugInstCode: "67",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر 12 ساعت",
  },
  {
    drugInstId: 68,
    drugInstCode: "68",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر 24 ساعت",
  },
  {
    drugInstId: 69,
    drugInstCode: "69",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "يک روز در ميان",
  },
  {
    drugInstId: 70,
    drugInstCode: "70",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "قبل از خواب",
  },
  {
    drugInstId: 71,
    drugInstCode: "71",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر روز صبح",
  },
  {
    drugInstId: 72,
    drugInstCode: "72",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هفته اي يک بار",
  },
  {
    drugInstId: 73,
    drugInstCode: "73",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر دو هفته يک بار",
  },
  {
    drugInstId: 74,
    drugInstCode: "74",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر سه هفته يک بار",
  },
  {
    drugInstId: 75,
    drugInstCode: "1511000175108",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "هر چهار هفته يک بار",
  },
  {
    drugInstId: 76,
    drugInstCode: "76",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "در صورت نياز",
  },
  {
    drugInstId: 77,
    drugInstCode: "77",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "طبق دستور",
  },
  {
    drugInstId: 78,
    drugInstCode: "78",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "ماهي يک بار",
  },
  {
    drugInstId: 79,
    drugInstCode: "79",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "سالي يک بار",
  },
  {
    drugInstId: 80,
    drugInstCode: "80",
    drugInstSumry: null,
    drugInstLatin: null,
    drugInstConcept: "ساير",
  },
  {
    drugInstId: 81,
    drugInstCode: "81",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "صبح ها",
  },
  {
    drugInstId: 82,
    drugInstCode: "82",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "عصرها",
  },
  {
    drugInstId: 83,
    drugInstCode: "83",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "شب ها",
  },
  {
    drugInstId: 84,
    drugInstCode: "84",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "هر 6 ماه",
  },
  {
    drugInstId: 85,
    drugInstCode: "85",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "هر 2 ماه",
  },
  {
    drugInstId: 86,
    drugInstCode: "86",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "هر 3 ماه",
  },
  {
    drugInstId: 87,
    drugInstCode: "87",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "هفته  0 و 2 و 6",
  },
  {
    drugInstId: 88,
    drugInstCode: "88",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "هر 8 هفته",
  },
  {
    drugInstId: 89,
    drugInstCode: "89",
    drugInstSumry: "NEW",
    drugInstLatin: null,
    drugInstConcept: "هر 6 هفته",
  },
];
export default data2;
