const Data3 = [
  {
    drugUsageId: 0,
    drugUsageCode: "0",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "ساير",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 1,
    drugUsageCode: "1",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "با معده پر (بعد از غذا)",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 2,
    drugUsageCode: "2",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: " با معده خالي (قبل از غذا)",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 3,
    drugUsageCode: "3",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "همراه با غذا",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 4,
    drugUsageCode: "4",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "ناشتا (نيم ساعت قبل صبحانه)",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 5,
    drugUsageCode: "5",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "زيرزباني",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 6,
    drugUsageCode: "6",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "صبح ها",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 7,
    drugUsageCode: "7",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "عصر ها",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 8,
    drugUsageCode: "8",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "شب ها",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 9,
    drugUsageCode: "9",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "قبل از نهار و شام",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 10,
    drugUsageCode: "10",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "بعد از نهار و شام ",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 11,
    drugUsageCode: "11",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "موضعي بماليد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 12,
    drugUsageCode: "12",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "شستشو دهيد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 13,
    drugUsageCode: "13",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "سر شستشو شود",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 14,
    drugUsageCode: "14",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "بدن شستشو شود",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 15,
    drugUsageCode: "15",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "سر / بدن شستشو شود",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 16,
    drugUsageCode: "16",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "چشم را شستشو دهيد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 17,
    drugUsageCode: "17",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "موضع را شستشو دهيد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 18,
    drugUsageCode: "18",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "شب بماليد صبح بشوييد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 19,
    drugUsageCode: "19",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "از گردن به پايين بماليد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 20,
    drugUsageCode: "20",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "استعمال واژينال",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 21,
    drugUsageCode: "21",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "استعمال مقعدي",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 22,
    drugUsageCode: "22",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "اسپري شود",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 23,
    drugUsageCode: "23",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "در صورت نياز",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 24,
    drugUsageCode: "24",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "طبق دستور",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 25,
    drugUsageCode: "25",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "عضلاني (im)-تزريق پس از تست",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 26,
    drugUsageCode: "26",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "(infu) انفوزيون وريدي ",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 27,
    drugUsageCode: "27",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "عضلاني (im)",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 28,
    drugUsageCode: "28",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "وريدي (iv)",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 29,
    drugUsageCode: "29",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "زير پوستي (sc)",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 30,
    drugUsageCode: "30",
    drugUsageSumry: null,
    drugUsageLatin: null,
    drugUsageConcept: "داخل سرم",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 31,
    drugUsageCode: "31",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "در چشم ",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 32,
    drugUsageCode: "32",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "در بيني",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 33,
    drugUsageCode: "33",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "در گوش",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 34,
    drugUsageCode: "34",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "خوراکي",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 35,
    drugUsageCode: "35",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "استنشاق شود",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 36,
    drugUsageCode: "36",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "در آب حل شده سپس ميل شود",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 37,
    drugUsageCode: "37",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "کد 6و7و8 حذف گردد",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 38,
    drugUsageCode: "38",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "در دهان چرخانده و دور بريزيد.",
    visible: "1",
    drugFormCode: null,
  },
  {
    drugUsageId: 39,
    drugUsageCode: "39",
    drugUsageSumry: null,
    drugUsageLatin: "NEW",
    drugUsageConcept: "در موضع قرار دهيد.",
    visible: "1",
    drugFormCode: null,
  },
];
export default Data3;
