const namedru = [
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " CYTARABINE INJECTION, POWDER, FOR SOLUTION  100MG",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "52393",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " DEFERIPRONE TABLET, EFFERVESCENT ORAL 500 mg",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "50438",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " DOXORUBICIN HYDROCHLORIDELIPOSOMAL 2 mg/1mL 10m ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "50610",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " IMMUNE GLOBULIN INJECTION PARENTERAL 200 mg/1mL 5MILLILITER",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "50081",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      " KARNOFEN COMPOUND CAPSULE, LIQUID FILLED ORAL 325 mg/40 mg/200 mg",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "08979",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "68426",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: " PROSTAGLANDIN E1(ALPROSTADIL) POWDERFOR SOLUTION 20 ug ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "08777",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "(18F) FLUDEOXYGLUCOSE  10 mCi PARENTERAL INJECTION, SOLUTION",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "50181",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "(exipen)قلم تزريق انسولين",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "66677",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "21ST CENTURY HAIR, SKIN &amp; NAILS TABLET ORAL",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "80000",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "80000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "21ST CENTURY PRENATAL TABLET ORAL",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "80001",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "80001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "3,4 DIAMINOPYRIDINE TABLET ORAL 20 mg",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "18384",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "66173",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "3G MAX CAPSULE ORAL",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "92969",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "92969",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "3SULFA CREAM VAGINAL 3.42 %/2.86 %/3.7 % 78 g",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "01264",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "62584",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "5-HTP CAPSULE ORAL 100 mg",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "81144",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "81144",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "01",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "5-METHYLTETRAHYDROFOLATE TABLET ORAL 500 ug",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: "81145",
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "81145",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
];

export default namedru;
