const Phisio = [
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-ارزيابي جامع کاردرماني يا شغلي جهت برنامه ريزي براي کاردرماني بيمار براي يک دوره درمان",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901648-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-به کارگيري روش ها  و تکنيک هاي کاردرماني شامل استفاده از يک يا چند مورد از فعاليت هاي کاردرماني براي يک جلسه حداقل 30 دقيقه اي ، آموزش بازگشت فرد به جامعه يا کار، آموزش مديريت منزل، آموزش حرکت با ويلچر، آموزش راه رفتن، آموزش هندلينگ بيمار يا خانواده وي، مداخلات کاردرماني در ضايعات دست پس از جراحي، مداخلات کاردرماني در بخش هاي مراقبت ويژه و ساير روش ها يا مداليته هاي کاردرماني)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901650-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "-به کارگيري روش‌ها و تکنيک‌هاي کاردرماني شامل استفاده از يک يا چند مورد از فعاليت‌هاي کاردرماني براي يک جلسه حداقل 60 دقيقه‌‌اي  مطابق با استانداردهاي ابلاغي وزارت بهداشت، درمان و آموزش پزشکي",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901655-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "-فيزوتراپي دو اندام فوقاني و دو اندام تحتاني ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901645-904",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "-فيزيو تراپي دو اندام فوقاني و اندام تحتاني چپ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901645-901",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "-فيزيوتراپي دو اندام تحتاني و اندام فوقاني چپ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901645-903",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "-فيزيوتراپي دو اندام تحتاني و اندام فوقاني راست ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901645-902",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      '118345003-" استفاده از دستگاه ليزر پرتوان جهت کاربردهاي عصبي-اسکلتي-عضلاني؛ به ازاي هر جلسه (عمل مستقل)مطابق با استانداردهاي ابلاغي وزارت بهداشت، درمان و آموزش پزشکي "',
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901665-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "118481004-Taping Kinesio",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901690-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "15081005-توانبخشي ريوي شامل ارزيابي پزشکي، مانيتورينگ قلبي، اکسيژن درماني و ورزش درماني؛ به ازاي هر جلسه",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901683-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "180292008-Body Jacket ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901694-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "180313001-Cock Up(استاتيک دست) ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901695-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "183306002-فيزيوتراپي ناحيه عضلات کف لگن",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-101",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "1870001-Halo vest (چهار بار کربني) (هزينه مواد مصرفي به صورت جداگانه قابل محاسبه و اخذ مي‌باشد)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901691-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "21825005-دياترمي",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901646-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "228595003-کنترل استفاده از ارتز يا پروتز، بيمار قبلي ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901705-002",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "229065009-تمرين درماني ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901662-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "229488002-ماساژ يا تکنيک هاي درماني دستي براي لنف ادما ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901662-101",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "229594008-توانبخشي فعال DBC (Documented Based Care) براي ستون فقرات و اندام‌ها؛ هر جلسه",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901685-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "2517002-اقدامات طب توانبخشي جهت بيماران سكته مغزي، ضربه مغزي، ضايعات نخاعي شامل ارزيابي پزشك، تجويز روشهاي توانبخشي، آموزش فعاليتهاي روزمره زندگي، مشاوره تغذيه، خدمات روانشناسي و ورزش درماني توسط متخصص طب فيزيکي به ازاي هر جلسه(اين کد با کدهاي 901620 الي901646 و 901670 قبل گزارش نيست)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901673-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "252491004-Whole Body Vibration (WBV) ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901677-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "252636004-مانومتري اسفنکتر مقعد (روش",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-108",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "252757004-الکتروميوگرافي اسفنکتر (روش)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-105",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "252758009-الکتروميوگرافي اسفنکتر مقعد (روش)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-106",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "28150003-آموزش بيوفيدبک، با هر روشي ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900130-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "29203007-نوروفيدبک ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900137-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "312634001-کنترل استفاده از ارتز يا پروتز، بيمار قبلي ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901705-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "313092005-استفاده از دستگاه Magnetic Field Therapy جهت توانبخشي اندام‌ها؛ به ازاي هر جلسه منطبق با استانداردهاي ابلاغي وزارت بهداشت، درمان و آموزش پزشکي (عمل مستقل)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901680-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "34431008-فيزيوتراپي قفسه سينه بدون فيزيوتراپي اندام ها با يا بدون مداليته هاي فيزيكي شامل تمرين درماني و ماساژ بيماران بستري (در صورت درخواست پزشک معالج در بخش هاي مراقبت ويژه (CCU و ICU) و بخش هاي جراحي توراکس و ريه براي هر تعداد جلسه در هر روز بستري و رعايت مدت زمان استاندارد حداقل 20 دقيقه تحت پوشش بيمه پايه مي باشد) (اين کد را با کد 901640 قابل گزراش و اخذ نمي باشد) (مطابق با استانداردهاي ابلاغي وزارت بهداشت، درمان و آموزش پزشکي)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901636-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "36430006-وفيدبک الکتروميوگرافيک (رژيم/درمان)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-100",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "37030005-آموزش و فيتينگ ارتز (شامل ارزيابي و فيتينگ که در جاي ديگر گزارش نشده است) اندام‌هاي فوقاني، اندام‌هاي تحتاني و يا تنه ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901706-002",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "385958001-مراقبت از پرينه (رژيم/درماني)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-104",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "385976008-فيزيوتراپي کولورکتال",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-103",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "389082000-فيزيوتراپي جهت رفع يبوست",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-102",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "410155007-ارزيابي جامع کاردرماني يا شغلي جهت برنامه ريزي براي کاردرماني بيمار براي يک دوره درمان",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901630-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "419251004-آموزش با پروتز، اندامهاي فوقاني و يا تحتاني",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901700-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "423733006-استفاده از CPM يا ليزر کم توان براي توانبخشي اندام‌ها",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901625-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      '439794000-"استفاده از دستگاه ESWT (Exteracorporeal Shock Wave Therapy) با توان کم، جهت درمان دردهاي اسکلتي-عضلاني و ترميم بافت نرم؛ به ازاي هر جلسه (عمل مستقل)منطبق با استانداردهاي ابلاغي وزارت بهداشت، درمان و آموزش پزشکي "',
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901670-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "462421009-Application of below knee cast brace with ankle hinges (procedure)\n",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901697-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "464544009-TLSO ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901693-002",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "464915004-TLSO ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901693-001",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "46903006- آب درماني ",
    srvName2: null,
    srvBimSw: "1",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901660-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "470064003-LSO ",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901692-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "470672002-Knee Brace (HO)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901699-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "470732004-Hip Brace (HO)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901698-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "47387005-اقدامات طب توانبخشي جهت بيماران سكته مغزي، ضربه مغزي، ضايعات نخاعي شامل ارزيابي پزشك، تجويز روشهاي توانبخشي، آموزش فعاليتهاي روزمره زندگي، مشاوره تغذيه، خدمات روانشناسي و ورزش درماني توسط متخصص طب فيزيکي به ازاي هر جلسه(اين کد با کدهاي 901620 الي901646 و 901670 قبل گزارش نيست)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901673-003",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "49376005-الکتروميوگرافي اسفنکتر مجراي ادرار (روش)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "900135-107",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName: "701407007-Sarmiento Brace (استاتيک بازو)",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901696-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
  {
    srvId: null,
    srvType: {
      srvType: "13",
      srvTypeDes: null,
      status: null,
      statusstDate: null,
      custType: null,
      prescTypeId: null,
    },
    srvCode: null,
    srvName:
      "713374001-اسکن استاتيک کف پا (Foot Scan) براي تعيين نقاط فشاري کف پا و تجويز کفي و يا اورتز مناسب",
    srvName2: null,
    srvBimSw: "2",
    srvSex: null,
    srvPrice: null,
    srvPriceDate: null,
    doseCode: null,
    parTarefGrp: null,
    status: null,
    statusstDate: null,
    bGType: null,
    gSrvCode: null,
    agreementFlag: null,
    isDeleted: null,
    visible: null,
    dentalServiceType: null,
    wsSrvCode: "901675-000",
    hosprescType: null,
    countIsRestricted: null,
    terminology: null,
    srvCodeComplete: null,
  },
];
export default Phisio;
