const complaints = [
  {
    id: 135,
    code: 102608004,
    displayName: "اشتهاي بيش از حد",
    englishName: "Excessive appetite (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 266,
    code: 163540009,
    displayName: "کاهش حرکت جنين",
    englishName: "On examination - fetal movement diminished (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 267,
    code: 164307008,
    displayName: "تب ناگهاني",
    englishName: "On examination - fever - acute rise (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 268,
    code: 164312009,
    displayName: "تب متناوب",
    englishName: "On examination - fever - intermittent (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 269,
    code: 163588007,
    displayName: "در حال تشنج",
    englishName: "On examination - fit/convulsion (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 270,
    code: 164472002,
    displayName: "طبيعي بودن پاها در معاينه",
    englishName: "On examination - legs - no abnormality detected (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 271,
    code: 164186007,
    displayName: "ترشحات چرکي بيني",
    englishName: "On examination - nasal discharge - mucopurulent (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 272,
    code: 268982000,
    displayName: "قرمزي در گلو",
    englishName: "On examination - pharynx hyperemic (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 273,
    code: 164017008,
    displayName: "پتوز پلک",
    englishName: "On examination - ptosis present (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 274,
    code: 164023003,
    displayName: "تنگي مردمک چشم",
    englishName: "On examination - pupil small (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 275,
    code: 163245000,
    displayName: "حساسيت رحم و ريباند",
    englishName: "On examination - rebound - hypogastrium (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 276,
    code: 163781003,
    displayName: "طبيعي بودن رفلکس ها",
    englishName: "On examination - reflexes normal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 277,
    code: 163358002,
    displayName: "تندرس پهلوها",
    englishName: "On examination - renal angle tenderness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 278,
    code: 164184005,
    displayName: "ابريزش بيني",
    englishName: "On examination - rhinorrhea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 279,
    code: 164162005,
    displayName: "بزرگي طحال",
    englishName: "On examination - splenomegaly (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 280,
    code: 164568004,
    displayName: "SLR مثبت",
    englishName: "On examination - straight leg raising (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 281,
    code: 164237002,
    displayName: "تورم پرده گوش",
    englishName: "On examination - tympanic membrane bulging (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 282,
    code: 164236006,
    displayName: "پرده گوش قرمز در معاينه",
    englishName: "On examination - tympanic membrane red (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 283,
    code: 268913004,
    displayName: "اختلال هوشياري و يا کما",
    englishName: "On examination - unconscious/comatose (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 284,
    code: 163410005,
    displayName: "تندرس رحم در معاينه واژينال",
    englishName:
      "On examination - vaginal examination - uterine tenderness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 285,
    code: 268987006,
    displayName: "وزيکول پوستي",
    englishName: "On examination - vesicles (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 286,
    code: 274399004,
    displayName: "خلط خوني",
    englishName: "On examination blood in sputum (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 287,
    code: 75431008,
    displayName: "سوفل غير طبيعي",
    englishName: "Organic heart murmur (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 288,
    code: 62744007,
    displayName: "ارتوپنه",
    englishName: "Orthopnea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 289,
    code: 16001004,
    displayName: "دردگوش",
    englishName: "Otalgia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 290,
    code: 22253000,
    displayName: "درد",
    englishName: "Pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 291,
    code: 41652007,
    displayName: "درد در چشم",
    englishName: "Pain in eye (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 292,
    code: 10601006,
    displayName: "درد در اندام تحتاني",
    englishName: "Pain in lower limb (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 293,
    code: 162397003,
    displayName: "گلودرد",
    englishName: "Pain in throat (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 294,
    code: 53430007,
    displayName: "درد پستان",
    englishName: "Pain of breast (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 295,
    code: 387638003,
    displayName: "مفصل گرم ،حساس متورم",
    englishName: "Painful swelling of joint (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 296,
    code: 267029006,
    displayName: "رنگ پريدگي",
    englishName: "Pale - symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 297,
    code: 719640000,
    displayName: "ملتحمه رنگ پريده",
    englishName: "Pale conjunctiva (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 298,
    code: 719192005,
    displayName: "لثه رنگ پريده",
    englishName: "Pale gingiva (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 299,
    code: 719193000,
    displayName: "رنگ پريدگي ناخن",
    englishName: "Pale nail bed (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 300,
    code: 719637000,
    displayName: "زبان رنگ پريده",
    englishName: "Pale tongue (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 301,
    code: 80313002,
    displayName: "تپش قلب",
    englishName: "Palpitations (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 302,
    code: 445328000,
    displayName: "پاپول پوستي",
    englishName: "Papule of skin (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 303,
    code: 91019004,
    displayName: "خواب رفتن و سوزن سوزن شدن دست و پاها",
    englishName: "Paresthesia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 304,
    code: 43025008,
    displayName: "سرفه پاروکسيسمال",
    englishName: "Paroxysmal cough (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 305,
    code: 18425006,
    displayName: "اسهال ابکي آب برنجي",
    englishName: "Passage of rice water stools (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 306,
    code: 289532003,
    displayName: "دفع لخته از واژن",
    englishName: "Passing clots vaginally (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 307,
    code: 225565007,
    displayName: "درد پرينه",
    englishName: "Perineal pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 308,
    code: 289900009,
    displayName: "درد قاعدگي",
    englishName: "Period pain present (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 309,
    code: 284523002,
    displayName: "سرفه مداوم",
    englishName: "Persistent cough (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 310,
    code: 279047007,
    displayName: "درد ماندگار پس از اقدام درماني",
    englishName: "Persistent pain following procedure (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 311,
    code: 271813007,
    displayName: "پتشي",
    englishName: "Petechiae (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 312,
    code: 102618009,
    displayName: "خشکي حلق",
    englishName: "Pharyngeal dryness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 313,
    code: 409668002,
    displayName: "نورگريزي (ترس افراطي و دوري از نور)",
    englishName: "Photophobia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 314,
    code: 248004009,
    displayName: "خشونت فيزيکي",
    englishName: "Physical aggression (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 315,
    code: 284521000,
    displayName: "ادم گوده گذار",
    englishName: "Pitting edema (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 316,
    code: 28442001,
    displayName: "پرادراري",
    englishName: "Polyuria (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 317,
    code: 26329005,
    displayName: "تمرکز ضعيف",
    englishName: "Poor concentration (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 318,
    code: 266960003,
    displayName: "تمايل کم به کار کردن",
    englishName: "Poor work record (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 319,
    code: 48880000,
    displayName: "خونريزي يا لکه بيني بعد از مقاربت",
    englishName: "Postcoital bleeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 320,
    code: 76742009,
    displayName: "خونريزي پس از يائسگي",
    englishName: "Postmenopausal bleeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 321,
    code: 373717006,
    displayName: "يائسگي زودرس",
    englishName: "Premature menopause (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 322,
    code: 32590007,
    displayName: "امنوره قبل از يائسگي",
    englishName: "Premenopausal amenorrhea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 323,
    code: 289560001,
    displayName: "افزايش ترشحات واژينال",
    englishName: "Profuse vaginal discharge (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 324,
    code: 248586000,
    displayName: "بازدم طولاني",
    englishName: "Prolonged expiration (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 136,
    code: 267023007,
    displayName: "خوردن بيش از حد - پلي فاژي",
    englishName: "Excessive eating - polyphagia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 3,
    code: 74704000,
    displayName: "درد شکم و  پهلوها",
    englishName: "Abdominal pain through to back (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 4,
    code: 43478001,
    displayName: "تندرنس شکم",
    englishName: "Abdominal tenderness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 5,
    code: 284973007,
    displayName: "قادر به لباس پوشيدن",
    englishName: "Able to dress (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 6,
    code: 288884008,
    displayName: "قادر به غذا خوردن است",
    englishName: "Able to eat (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 7,
    code: 282600008,
    displayName: "قادر به پرش",
    englishName: "Able to jump (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 8,
    code: 285170004,
    displayName: "توانايي شناسايي چهره ها",
    englishName: "Able to recognize faces (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 9,
    code: 285168008,
    displayName: "قادر به تشخيص چهره",
    englishName: "Able to recognize faces by sight (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 10,
    code: 282620009,
    displayName: "قابليت غلت زدن",
    englishName: "Able to roll (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 11,
    code: 282474007,
    displayName: "قادر به دويدن است",
    englishName: "Able to run (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 12,
    code: 302040002,
    displayName: "نشستن بدون کمک",
    englishName: "Able to sit unsupported (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 13,
    code: 288375004,
    displayName: "توانايي ورق زدن",
    englishName: "Able to turn pages (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 14,
    code: 25786006,
    displayName: "رفتار غير طبيعي",
    englishName: "Abnormal behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 15,
    code: 386813002,
    displayName: "اختلال تنفسي",
    englishName: "Abnormal breathing (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 16,
    code: 22325002,
    displayName: "راه رفتن غير طبيعي",
    englishName: "Abnormal gait (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 17,
    code: 361136003,
    displayName: "ضربان قلب غير طبيعي",
    englishName: "Abnormal heart beat (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 18,
    code: 225606002,
    displayName: "حرکت غير طبيعي اندامها",
    englishName: "Abnormal movement (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 19,
    code: 67683007,
    displayName: "غير طبيعي بودن نبض",
    englishName: "Abnormal pulse (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 20,
    code: 46670006,
    displayName: "رفلکسهاي غير طبيعي",
    englishName: "Abnormal reflex (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 21,
    code: 84800009,
    displayName: "جريان ادرار غير طبيعي",
    englishName: "Abnormal urinary stream (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 22,
    code: 301822002,
    displayName: "خونريزي غير طبيعي واژينال",
    englishName: "Abnormal vaginal bleeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 23,
    code: 7973008,
    displayName: "اختلال بينايي",
    englishName: "Abnormal vision (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 24,
    code: 237804005,
    displayName: "عدم وجود بيضه",
    englishName: "Absent testes (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 25,
    code: 70396004,
    displayName: "مدفوع سفيد",
    englishName: "Acholic stool (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 26,
    code: 116290004,
    displayName: "درد حاد شکمي",
    englishName: "Acute abdominal pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 27,
    code: 373895009,
    displayName: "ناراحتي حاد تنفسي",
    englishName: "Acute respiratory distress (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 28,
    code: 440575001,
    displayName: "ايروفوبي",
    englishName: "Aerophobia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 29,
    code: 61372001,
    displayName: "رفتار پرخاشگرانه",
    englishName: "Aggressive behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 30,
    code: 249473004,
    displayName: "تغير اشتها  (کم يا زياد)",
    englishName: "Altered appetite (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 31,
    code: 14302001,
    displayName: "قطع قاعدگي",
    englishName: "Amenorrhea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 32,
    code: 68653001,
    displayName: "درد مقعد",
    englishName: "Anal pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 33,
    code: 2472002,
    displayName: "انوري",
    englishName: "Anuria (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 34,
    code: 48694002,
    displayName: "اضطراب",
    englishName: "Anxiety (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 35,
    code: 300895004,
    displayName: "حملات اضطرابي",
    englishName: "Anxiety attack (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 36,
    code: 248661003,
    displayName: "تغيير محل ضربه Apex",
    englishName: "Apex beat displaced (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 37,
    code: 1023001,
    displayName: "قطع تنفس (آپنه)",
    englishName: "Apnea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 38,
    code: 13791008,
    displayName: "ضعف",
    englishName: "Asthenia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 39,
    code: 18197001,
    displayName: "ويز آسمي",
    englishName: "Asthmatoid wheeze (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 40,
    code: 391155006,
    displayName: "در خطر آسيب رساندن به ديگران",
    englishName: "At risk of harming others (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 41,
    code: 161891005,
    displayName: "کمر درد",
    englishName: "Backache (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 42,
    code: 17986004,
    displayName: "سرفه پارس مانند",
    englishName: "Barking cough (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 43,
    code: 78077007,
    displayName: "همسر ازاري",
    englishName: "Battered spouse syndrome (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 44,
    code: 43994002,
    displayName: "افت فعاليت فيزيکي",
    englishName: "Behavior showing reduced motor activity (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 45,
    code: 80670004,
    displayName: "ظاهر غير عادي، عدم رعايت بهداشت فردي",
    englishName: "Bizarre personal appearance (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 46,
    code: 249366005,
    displayName: "خونريزي از بيني",
    englishName: "Bleeding from nose (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 47,
    code: 289530006,
    displayName: "خونريزي واژينال",
    englishName: "Bleeding from vagina (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 48,
    code: 86276007,
    displayName: "خونريزي لثه",
    englishName: "Bleeding gums (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 49,
    code: 249418002,
    displayName: "خونريزي مخاط دهاني",
    englishName: "Bleeding of oral mucosa (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 50,
    code: 34436003,
    displayName: "ادرار خوني",
    englishName: "Blood in urine (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 51,
    code: 111516008,
    displayName: "تاري ديد",
    englishName: "Blurring of visual image (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 52,
    code: 83765003,
    displayName: "بي حوصلگي و احساس دل گرفتگي",
    englishName: "Boredom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 53,
    code: 89164003,
    displayName: "توده پستاني",
    englishName: "Breast lump (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 54,
    code: 55222007,
    displayName: "حساس شدن پستان",
    englishName: "Breast tenderness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 55,
    code: 79879001,
    displayName: "بوي بد دهان",
    englishName: "Breath smells unpleasant (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 56,
    code: 161885008,
    displayName: "کبودي",
    englishName: "Bruising symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 57,
    code: 103019006,
    displayName: "فونتانل برجسته",
    englishName: "Bulging fontanelle (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 58,
    code: 445178008,
    displayName: "سوزش در ناحيه تناسلي",
    englishName: "Burning sensation of vagina (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 59,
    code: 271656000,
    displayName: "تريل قلبي",
    englishName: "Cardiac thrill (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 60,
    code: 301153003,
    displayName: "وجود نبض کاروتيد",
    englishName: "Carotid pulse present (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 61,
    code: 279084009,
    displayName: "احساس ناراحتي در قفسه سينه",
    englishName: "Chest discomfort (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 62,
    code: 39180009,
    displayName: "Dulness در دق ريه",
    englishName: "Chest dull to percussion (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 63,
    code: 298715006,
    displayName: "حرکت طبيعي قفسه سينه",
    englishName: "Chest movement normal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 64,
    code: 249674001,
    displayName: "پرهوايي ريه در CXR",
    englishName: "Chest over-expanded (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 65,
    code: 29857009,
    displayName: "درد قفسه سينه",
    englishName: "Chest pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 66,
    code: 9267009,
    displayName: "درد قفسه سينه در استراحت",
    englishName: "Chest pain at rest (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 67,
    code: 81953000,
    displayName: "درد قفسه سينه در هنگام فعاليت",
    englishName: "Chest pain on exertion (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 325,
    code: 248966006,
    displayName: "قاعدگي طول کشيده",
    englishName: "Prolonged periods (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 137,
    code: 17173007,
    displayName: "تشنگي شديد",
    englishName: "Excessive thirst (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 138,
    code: 224994002,
    displayName: "افزايش وزن بيش از حد",
    englishName: "Excessive weight gain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 139,
    code: 301791008,
    displayName: "ترشح اگزودا روي لوزه ها",
    englishName: "Exudate on tonsils (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 140,
    code: 246615006,
    displayName: "بستن چشم ها در پاسخ به نور مستقيم",
    englishName: "Eye closure in response to direct bright light (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 141,
    code: 37126005,
    displayName: "چهره گرفته و عبوس",
    englishName: "Facial grimacing (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 142,
    code: 278528006,
    displayName: "تورم صورت",
    englishName: "Facial swelling (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 143,
    code: 84229001,
    displayName: "خستگي و ضعف عضلاني",
    englishName: "Fatigue (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 144,
    code: 1402001,
    displayName: "ترس",
    englishName: "Fear (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 145,
    code: 276242008,
    displayName: "ترس از اب",
    englishName: "Fear of water (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 146,
    code: 24199005,
    displayName: "احساس آشفتگي",
    englishName: "Feeling agitated (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 147,
    code: 75408008,
    displayName: "احساس عصبانيت",
    englishName: "Feeling angry (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 148,
    code: 17029006,
    displayName: "نااميدي",
    englishName: "Feeling despair (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 149,
    code: 248223005,
    displayName: "احساس ضعف",
    englishName: "Feeling faint (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 150,
    code: 7571003,
    displayName: "احساس گناه",
    englishName: "Feeling guilt (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 151,
    code: 307077003,
    displayName: "احساس نااميدي",
    englishName: "Feeling hopeless (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 152,
    code: 55929007,
    displayName: "بي قراري و تحريک پذيري",
    englishName: "Feeling irritable (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 153,
    code: 424196004,
    displayName: "عصبي بودن",
    englishName: "Feeling nervous (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 154,
    code: 420038007,
    displayName: "احساس ناراحتي",
    englishName: "Feeling unhappy (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 155,
    code: 249045009,
    displayName: "شنيده شدن صداي قلب جنين",
    englishName: "Fetal heart sounds present (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 156,
    code: 43673002,
    displayName: "سوفل قلب جنين",
    englishName: "Fetal souffle (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 157,
    code: 386661006,
    displayName: "تب",
    englishName: "Fever (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 158,
    code: 426000000,
    displayName: "تب بالاي 38 درجه",
    englishName: "Fever greater than 100.4 Fahrenheit (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 159,
    code: 274640006,
    displayName: "تب و لرز",
    englishName: "Fever with chills (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 160,
    code: 267026004,
    displayName: "پرنوشي",
    englishName: "Finding of excessive fluid intake (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 161,
    code: 365400002,
    displayName: "ظهور علايم بلوغ",
    englishName: "Finding of puberty stage (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 162,
    code: 62640008,
    displayName: "رال هاي fine در قاعده ريه ها",
    englishName: "Fine respiratory crackles (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 163,
    code: 247355005,
    displayName: "درد پهلو",
    englishName: "Flank pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 164,
    code: 250076001,
    displayName: "تونيسيته عضلاني غير طبيعي",
    englishName: "Fluctuating muscle tone (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 165,
    code: 55533009,
    displayName: "فراموشي",
    englishName: "Forgetful (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 166,
    code: 278616006,
    displayName: "شکستگي دندان",
    englishName: "Fractured denture (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 167,
    code: 2170000,
    displayName: "ريتم گالوپ",
    englishName: "Gallop rhythm (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 168,
    code: 23141003,
    displayName: "تنفس منقطع و غيرموثر",
    englishName: "Gasping for breath (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 169,
    code: 267062003,
    displayName: "علائم دستگاه ادراري تناسلي",
    englishName: "Genitourinary symptoms (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 170,
    code: 110342004,
    displayName: "تورم و قرمزي لثه ها",
    englishName: "Gingival erythema (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 171,
    code: 62085005,
    displayName: "تنفس گرانتينگ (شبه ناله کردن)",
    englishName: "Grunting respiration (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 172,
    code: 7011001,
    displayName: "توهم",
    englishName: "Hallucinations (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 173,
    code: 735237008,
    displayName: "عادات غلط دهاني",
    englishName: "Harmful oral hygiene habit (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 174,
    code: 25064002,
    displayName: "سر درد",
    englishName: "Headache (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 175,
    code: 88610006,
    displayName: "سوفل قلبي",
    englishName: "Heart murmur (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 176,
    code: 123824001,
    displayName: "سمع غير طبيعي قلب",
    englishName: "Heart sounds abnormal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 177,
    code: 16331000,
    displayName: "سوزش سردل",
    englishName: "Heartburn (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 178,
    code: 405729008,
    displayName: "مدفوع خوني",
    englishName: "Hematochezia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 179,
    code: 66857006,
    displayName: "خلط خوني",
    englishName: "Hemoptysis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 180,
    code: 50219008,
    displayName: "خشونت صدا",
    englishName: "Hoarse (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 181,
    code: 44548000,
    displayName: "رفتار بيش فعال",
    englishName: "Hyperactive behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 182,
    code: 86854008,
    displayName: "افزايش رفلکس هاي تاندوني",
    englishName: "Hyperreflexia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 183,
    code: 64964006,
    displayName: "صدايي با رزنانس بالا در دق",
    englishName: "Hyperresonance (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 184,
    code: 433332006,
    displayName: "کمبود دريافت کلسيم از رژيم غذايي",
    englishName: "Inadequate dietary intake of calcium (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 185,
    code: 249287002,
    displayName: "ادرار ناقص",
    englishName: "Incomplete urination (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 186,
    code: 48340000,
    displayName: "بي اختياري",
    englishName: "Incontinence (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 187,
    code: 72042002,
    displayName: "بي اختياري مدفوع",
    englishName: "Incontinence of feces (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 188,
    code: 50427001,
    displayName: "افزايش زمان پر شدن مويرگ ها",
    englishName: "Increased capillary filling time (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 189,
    code: 162116003,
    displayName: "افزايش دفعات ادرار",
    englishName: "Increased frequency of urination (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 190,
    code: 165245003,
    displayName: "راه رفتن بدون کمک",
    englishName: "Independent walking (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 191,
    code: 161838002,
    displayName: "مشکل تغذيه نوزاد",
    englishName: "Infant feeding problem (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 192,
    code: 298160000,
    displayName: "التهاب مفصل",
    englishName: "Inflamed joint (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 193,
    code: 281795003,
    displayName: "لوزه هاي ملتهب",
    englishName: "Inflamed tonsils (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 194,
    code: 719401001,
    displayName: "گفتار قابل فهم",
    englishName: "Intelligible speech (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 195,
    code: 77957000,
    displayName: "تب متناوب",
    englishName: "Intermittent fever (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 196,
    code: 80585000,
    displayName: "احساس سرما",
    englishName: "Intolerant of cold (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 197,
    code: 80182007,
    displayName: "قاعدگي نامنظم",
    englishName: "Irregular periods (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 198,
    code: 418290006,
    displayName: "خارش",
    englishName: "Itching (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 199,
    code: 74776002,
    displayName: "خارش چشم",
    englishName: "Itching of eye (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 200,
    code: 418363000,
    displayName: "خارش پوست",
    englishName: "Itching of skin (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 201,
    code: 18165001,
    displayName: "زردي",
    englishName: "Jaundice (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 202,
    code: 248214007,
    displayName: "زردي پوست صورت",
    englishName: "Jaundiced appearance of face (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 203,
    code: 248418008,
    displayName: "زردي دست و پا",
    englishName: "Jaundiced appearance of limbs (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 204,
    code: 57676002,
    displayName: "درد مفاصل",
    englishName: "Joint pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 205,
    code: 271771009,
    displayName: "تورم مفاصل",
    englishName: "Joint swelling (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 206,
    code: 299330008,
    displayName: "وجود ژنو والگوم در معاينه",
    englishName: "Knee joint valgus deformity (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 207,
    code: 248274002,
    displayName: "بي حالي",
    englishName: "Lack of energy (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 208,
    code: 40979000,
    displayName: "عدم فعاليت فيزيکي",
    englishName: "Lack of exercise (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 209,
    code: 724386005,
    displayName: "ضايعات ناحيه تناسلي",
    englishName: "Lesion of genitalia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 210,
    code: 214264003,
    displayName: "بي حالي",
    englishName: "Lethargy (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 211,
    code: 112104007,
    displayName: "درد موضعي",
    englishName: "Localized pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 212,
    code: 79890006,
    displayName: "از دست دادن اشتها",
    englishName: "Loss of appetite (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 213,
    code: 247796005,
    displayName: "لذت نبردن",
    englishName: "Loss of capacity for enjoyment (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 214,
    code: 278040002,
    displayName: "ريزش مو",
    englishName: "Loss of hair (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 215,
    code: 247753000,
    displayName: "از دست دادن علاقه",
    englishName: "Loss of interest (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 216,
    code: 279039007,
    displayName: "درد کمر",
    englishName: "Low back pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 217,
    code: 705000008,
    displayName: "از دست دادن کنترل خود",
    englishName: "Low self-control (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 218,
    code: 54586004,
    displayName: "درد زير شکم",
    englishName: "Lower abdominal pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 219,
    code: 298673002,
    displayName: "ستون فقرات کمري حساس در لمس",
    englishName: "Lumbar spine - tender (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 220,
    code: 367391008,
    displayName: "ناخوشي",
    englishName: "Malaise (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 221,
    code: 405273008,
    displayName: "شيدايي",
    englishName: "Manic mood (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 222,
    code: 300848003,
    displayName: "توده يا تورم",
    englishName: "Mass of body structure (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 223,
    code: 299703001,
    displayName: "توده گردني",
    englishName: "Mass of neck (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 224,
    code: 53929009,
    displayName: "وجود توده در کيسه بيضه ها",
    englishName: "Mass of scrotum (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 225,
    code: 386807006,
    displayName: "اختلال حافظه",
    englishName: "Memory impairment (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 226,
    code: 386692008,
    displayName: "منوراژي",
    englishName: "Menorrhagia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 227,
    code: 84292000,
    displayName: "تاخير در قاعدگي",
    englishName: "Menstrual period late (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 228,
    code: 9126005,
    displayName: "لکه بيني قاعدگي",
    englishName: "Menstrual spotting (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 229,
    code: 47437004,
    displayName: "عقب ماندگي",
    englishName: "Mental handicap (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 230,
    code: 18963009,
    displayName: "تغيير خلق",
    englishName: "Mood swings (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 231,
    code: 51885006,
    displayName: "تهوع مکرر صبحگاهي",
    englishName: "Morning sickness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 232,
    code: 249955006,
    displayName: "طبيعي بودن قدرت عضلاني اندام ها در معاينه",
    englishName: "Movement against resistance (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 233,
    code: 123640000,
    displayName: "خشکي مخاط",
    englishName: "Mucous membrane dryness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 234,
    code: 68962001,
    displayName: "درد عضلاني",
    englishName: "Muscle pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 235,
    code: 26544005,
    displayName: "ضعف عضلاني",
    englishName: "Muscle weakness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 236,
    code: 248568003,
    displayName: "تکان خوردن نامعمول پره هاي بيني",
    englishName: "Nasal flaring (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 237,
    code: 85023004,
    displayName: "رگورژيتاسيون از بيني",
    englishName: "Nasal regurgitation (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 238,
    code: 289190003,
    displayName: "صداي تودماغي",
    englishName: "Nasal voice (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 239,
    code: 422587007,
    displayName: "تهوع",
    englishName: "Nausea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 240,
    code: 102957003,
    displayName: "تظاهرات عصبي",
    englishName: "Neurological finding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 241,
    code: 42984000,
    displayName: "تعريق شبانه",
    englishName: "Night sweats (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 242,
    code: 162164007,
    displayName: "ترشح نوک پستان",
    englishName: "Nipple discharge symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 243,
    code: 139394000,
    displayName: "شب ادراري",
    englishName: "Nocturia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 244,
    code: 8009008,
    displayName: "شب ادراري",
    englishName: "Nocturnal enuresis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 245,
    code: 248573009,
    displayName: "تنفس صدادار",
    englishName: "Noisy respiration (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 246,
    code: 69840006,
    displayName: "شيردهي طبيعي",
    englishName: "Normal breast feeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 247,
    code: 289148009,
    displayName: "تغذيه طبيعي نوزاد",
    englishName: "Normal infant feeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 248,
    code: 103251002,
    displayName: "حرکت طبيعي چشم ها",
    englishName: "Normal ocular motility (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 249,
    code: 297126005,
    displayName: "وضعيت ادنکس طبيعي رحم",
    englishName: "Normal uterine adnexae (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 250,
    code: 373658006,
    displayName: "رفتار وسواسي",
    englishName: "Obsessive behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 251,
    code: 286731006,
    displayName: "شخصيت لجباز",
    englishName: "Obstinate character (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 252,
    code: 289561002,
    displayName: "ترشحات بدبوي واژينال",
    englishName: "Offensive vaginal discharge (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 253,
    code: 83128009,
    displayName: "اليگوري",
    englishName: "Oliguria (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 254,
    code: 164620004,
    displayName: "توده",
    englishName: "On examination - a lump (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 255,
    code: 164139008,
    displayName: "علامت کم خوني",
    englishName: "On examination - anemia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 256,
    code: 163036009,
    displayName: "افت فشارخون",
    englishName: "On examination - blood pressure decreased (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 257,
    code: 163482006,
    displayName: "قوام غير طبيعي توده در پستان",
    englishName: "On examination - breast lump consistency (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 258,
    code: 163472005,
    displayName: "توده پستان يا زير بغل",
    englishName: "On examination - breast lump- axillary tail (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 259,
    code: 163180006,
    displayName: "تنفس بدبو",
    englishName: "On examination - breath offensive-halitosis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 260,
    code: 162950006,
    displayName: "صداي تنفس طبيعي در معاينه",
    englishName: "On examination - breath sounds normal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 261,
    code: 163724008,
    displayName: "طبيعي بودن معاينه حسي و حس عمقي",
    englishName: "On examination - deep sensation normal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 262,
    code: 162776001,
    displayName: "افتادن شانه ها",
    englishName: "On examination - drooping/round shouldered (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 263,
    code: 164221008,
    displayName: "دردناک بودن لاله گوش",
    englishName: "On examination - ear auricle painful (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 264,
    code: 268918008,
    displayName: "ادم (ورم)",
    englishName: "On examination - edema (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 265,
    code: 162783008,
    displayName: "ادم پاها",
    englishName: "On examination - edema of legs (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 1,
    code: 271860004,
    displayName: "توده شکمي",
    englishName: "Abdominal mass (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 2,
    code: 21522001,
    displayName: "درد شکم",
    englishName: "Abdominal pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 68,
    code: 67909005,
    displayName: "تو کشيده شدن قفسه سينه",
    englishName: "Chest wall retraction (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 69,
    code: 43724002,
    displayName: "لرز",
    englishName: "Chill (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 70,
    code: 68154008,
    displayName: "سرفه مزمن",
    englishName: "Chronic cough (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 71,
    code: 704425001,
    displayName: "تب مزمن",
    englishName: "Chronic fever (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 72,
    code: 82423001,
    displayName: "درد مزمن",
    englishName: "Chronic pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 73,
    code: 40917007,
    displayName: "اختلال هوشياري و گيجي",
    englishName: "Clouded consciousness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 74,
    code: 47525004,
    displayName: "رال هاي خشن در سمع ريه",
    englishName: "Coarse respiratory crackles (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 75,
    code: 771542000,
    displayName: "انتهاي سرد",
    englishName: "Cold extremity (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 76,
    code: 766877008,
    displayName: "گريه هاي طولاني و ممتد نوزاد",
    englishName: "Constantly crying infant (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 77,
    code: 14760008,
    displayName: "يبوست",
    englishName: "Constipation (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 78,
    code: 49727002,
    displayName: "سرفه",
    englishName: "Cough (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 79,
    code: 55300003,
    displayName: "دردهاي کرامپي",
    englishName: "Cramp (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 80,
    code: 279093005,
    displayName: "دردهاي کرامپي",
    englishName: "Cramping pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 81,
    code: 162213003,
    displayName: "گريه زياد",
    englishName: "Crying, excessive (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 82,
    code: 219006,
    displayName: "مصرف کننده الکل",
    englishName: "Current drinker of alcohol (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 83,
    code: 417284009,
    displayName: "مصرف کننده فعلي مواد مخدر",
    englishName: "Current drug user (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 84,
    code: 3415004,
    displayName: "سيانوز",
    englishName: "Cyanosis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 85,
    code: 720001001,
    displayName: "ادرار زرد تيره",
    englishName: "Dark yellow urine (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 86,
    code: 64379006,
    displayName: "کاهش اشتها",
    englishName: "Decrease in appetite (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 87,
    code: 71781005,
    displayName: "کاهش قد",
    englishName: "Decrease in height (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 88,
    code: 443371007,
    displayName: "کاهش سطح هوشياري",
    englishName: "Decreased level of consciousness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 89,
    code: 425244000,
    displayName: "کاهش تورگور پوستي",
    englishName: "Decreased skin turgor (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 90,
    code: 360404009,
    displayName: "ظاهر غير طبيعي يا غير قرينه پستان",
    englishName: "Deformation of breast (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 91,
    code: 445144002,
    displayName: "بدشکلي اندامها",
    englishName: "Deformity of limb (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 92,
    code: 2073000,
    displayName: "هذيان",
    englishName: "Delusions (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 93,
    code: 366979004,
    displayName: "خلق افسرده",
    englishName: "Depressed mood (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 94,
    code: 62315008,
    displayName: "اسهال",
    englishName: "Diarrhea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 95,
    code: 275297005,
    displayName: "اسهال و استفراغ",
    englishName: "Diarrhea and vomiting, symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 96,
    code: 162020001,
    displayName: "مشکل در جويدن",
    englishName: "Difficulty chewing (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 97,
    code: 288857007,
    displayName: "مشکل در نوشيدن",
    englishName: "Difficulty drinking (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 98,
    code: 423238001,
    displayName: "اختلال در برقراري ارتباط اجتماعي",
    englishName: "Difficulty establishing relationships (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 99,
    code: 288986006,
    displayName: "مشکل در مکيدن",
    englishName: "Difficulty suckling (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 100,
    code: 308925008,
    displayName: "علايم گوارشي",
    englishName: "Digestive symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 101,
    code: 37125009,
    displayName: "گشادي مردمکها",
    englishName: "Dilated pupil (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 102,
    code: 413298002,
    displayName: "مشکل در انجام فعاليتهاي روزمره",
    englishName: "Disability affecting daily living (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 103,
    code: 246679005,
    displayName: "ترشح چشم",
    englishName: "Discharge from eye (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 104,
    code: 248952001,
    displayName: "ترشح در ناحيه تناسلي زنان",
    englishName: "Discharge from female genitalia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 105,
    code: 62476001,
    displayName: "اختلال جهت يابي",
    englishName: "Disorientated (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 106,
    code: 86485009,
    displayName: "محور غير طبيعي چشم ها (انحراف چشم)",
    englishName: "Dissociated deviation (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 107,
    code: 53888004,
    displayName: "خواب به هم ريخته",
    englishName: "Disturbance in sleep behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 108,
    code: 3006004,
    displayName: "اختلال هوشياري",
    englishName: "Disturbance of consciousness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 109,
    code: 8702009,
    displayName: "بي اختياري ادرار در طي روز",
    englishName: "Diurnal only enuresis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 110,
    code: 404640003,
    displayName: "سرگيجه",
    englishName: "Dizziness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 111,
    code: 288991007,
    displayName: "امتناع از مکيدن پستان جهت تغذيه توسط نوزاد",
    englishName: "Does not latch on to breast for feeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 112,
    code: 288985005,
    displayName: "امتناع از مکيدن",
    englishName: "Does not to suckle (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 113,
    code: 282193002,
    displayName: "از پله ها بالا مي رود",
    englishName: "Does walk up stairs (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 114,
    code: 62718007,
    displayName: "ابريزش از دهان",
    englishName: "Dribbling from mouth (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 115,
    code: 271782001,
    displayName: "خواب الودگي",
    englishName: "Drowsy (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 116,
    code: 16386004,
    displayName: "خشکي پوست",
    englishName: "Dry skin (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 117,
    code: 271669001,
    displayName: "خشکي زبان",
    englishName: "Dry tongue (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 118,
    code: 8011004,
    displayName: "ديزارتري",
    englishName: "Dysarthria (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 119,
    code: 71315007,
    displayName: "ديس پارونيا( مقاربت همراه با درد)",
    englishName: "Dyspareunia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 120,
    code: 267036007,
    displayName: "تنگي نفس",
    englishName: "Dyspnea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 121,
    code: 49650001,
    displayName: "احساس درد يا سوزش در هنگام ادرار کردن",
    englishName: "Dysuria (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 122,
    code: 302227002,
    displayName: "اکيموز",
    englishName: "Ecchymosis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 123,
    code: 267038008,
    displayName: "ادم",
    englishName: "Edema (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 124,
    code: 445088006,
    displayName: "ادم صورت",
    englishName: "Edema of face (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 125,
    code: 449707004,
    displayName: "ادم ساق پا",
    englishName: "Edema of lower leg (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 126,
    code: 102558002,
    displayName: "ادم اندام فوقاني",
    englishName: "Edema of the upper extremity (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 127,
    code: 102573001,
    displayName: "ادم ران پا",
    englishName: "Edema of thigh (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 128,
    code: 271808008,
    displayName: "ادم جنراليزه",
    englishName: "Edema, generalized (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 129,
    code: 421369008,
    displayName: "زودرنجي",
    englishName: "Emotional hypersensitivity (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 130,
    code: 198319004,
    displayName: "بزرگي رحم",
    englishName: "Enlarged uterus (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 131,
    code: 79922009,
    displayName: "درد اپي گاستر",
    englishName: "Epigastric pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 132,
    code: 444827008,
    displayName: "اريتم پوست",
    englishName: "Erythema of skin (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 133,
    code: 289293006,
    displayName: "پلي هيدرامنيوس",
    englishName: "Excessive amniotic fluid (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 134,
    code: 266601003,
    displayName: "خونريزي شديد يا مکرر قاعدگي",
    englishName: "Excessive and frequent menstruation (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 326,
    code: 236077008,
    displayName: "اسهال پايدار",
    englishName: "Protracted diarrhea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 327,
    code: 247011006,
    displayName: "مردمک هاي متقارن و گرد",
    englishName: "Pupil size and shape normal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 328,
    code: 423902002,
    displayName: "پورپورا",
    englishName: "Purpura (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 329,
    code: 423243008,
    displayName: "خروج ترشحات چرکي از چشم",
    englishName: "Purulent conjunctival discharge (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 330,
    code: 225550006,
    displayName: "خروج خون و چرک از محل زخم",
    englishName: "Purulent discharge from wound (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 331,
    code: 42192008,
    displayName: "خلط چرکي",
    englishName: "Purulent sputum (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 332,
    code: 289550005,
    displayName: "ترشحات چرکي و بدبو از مهبل",
    englishName: "Purulent vaginal discharge (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 333,
    code: 7520000,
    displayName: "تب بدون محل مشخص عفونت",
    englishName: "Pyrexia of unknown origin (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 334,
    code: 22447003,
    displayName: "افزايش فشار وريد جوگولار",
    englishName: "Raised jugular venous pressure (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 335,
    code: 35611005,
    displayName: "تندرس و ريباند شکم",
    englishName: "Rebound tenderness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 336,
    code: 427572007,
    displayName: "افزايش وزن اخير",
    englishName: "Recent weight gain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 337,
    code: 703630003,
    displayName: "قرمزي چشم",
    englishName: "Red eye (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 338,
    code: 300115000,
    displayName: "تورم و قرمزي لاله گوش",
    englishName: "Red pinna (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 339,
    code: 43408002,
    displayName: "رفلکس قرمز",
    englishName: "Red reflex (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 340,
    code: 69647007,
    displayName: "اشک ريزش خوني",
    englishName: "Red tears (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 341,
    code: 247761005,
    displayName: "اختلال در تمرکز",
    englishName: "Reduced concentration (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 342,
    code: 161844003,
    displayName: "کاهش مصرف مايعات",
    englishName: "Reduced fluid intake (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 343,
    code: 8357008,
    displayName: "کاهش ميل جنسي",
    englishName: "Reduced libido (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 344,
    code: 13164000,
    displayName: "کاهش دقت بينايي",
    englishName: "Reduced visual acuity (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 345,
    code: 302757007,
    displayName: "قاعدگي منظم",
    englishName: "Regular periods (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 346,
    code: 48409008,
    displayName: "رال ريوي",
    englishName: "Respiratory crackles (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 347,
    code: 271825005,
    displayName: "ديسترس تنفسي",
    englishName: "Respiratory distress (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 348,
    code: 300211002,
    displayName: "پاسخ به صداي زنگ",
    englishName: "Responds to high frequency sounds (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 349,
    code: 300202002,
    displayName: "برگشتن به طرف صداها",
    englishName: "Responds to voice (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 350,
    code: 247289009,
    displayName: "پاسخ به صداي آشنا",
    englishName: "Response to familiar voice (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 351,
    code: 162221009,
    displayName: "بي قراري",
    englishName: "Restlessness (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 352,
    code: 224398005,
    displayName: "تمايل کم به کار کردن",
    englishName: "Restricted work performance (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 353,
    code: 248047009,
    displayName: "فرار از خانه",
    englishName: "Running away from home (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 354,
    code: 248048004,
    displayName: "فرار از مدرسه",
    englishName: "Running away from school (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 355,
    code: 271867001,
    displayName: "بزاق غير طبيعي",
    englishName: "Saliva abnormal (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 356,
    code: 246975001,
    displayName: "زردي ملتحمه",
    englishName: "Scleral icterus (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 357,
    code: 53181008,
    displayName: "علائم خراش",
    englishName: "Scratch marks (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 358,
    code: 81916006,
    displayName: "جيغ کشيدن",
    englishName: "Screaming (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 359,
    code: 91175000,
    displayName: "تشنج",
    englishName: "Seizure (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 360,
    code: 365938009,
    displayName: "مشکل اعتماد به نفس",
    englishName: "Self-confidence finding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 361,
    code: 248062006,
    displayName: "رفتار خودزني",
    englishName: "Self-injurious behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 362,
    code: 248967002,
    displayName: "فواصل قاعدگي کوتاه",
    englishName: "Short menstrual periods (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 363,
    code: 297982009,
    displayName: "علايم پوستي",
    englishName: "Skin problem (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 364,
    code: 26677001,
    displayName: "خواب کم يا زياد",
    englishName: "Sleep pattern disturbance (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 365,
    code: 225583004,
    displayName: "لبخند زدن",
    englishName: "Smiles (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 366,
    code: 76067001,
    displayName: "عطسه",
    englishName: "Sneezing (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 367,
    code: 422650009,
    displayName: "انزواي اجتماعي",
    englishName: "Social isolation (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 368,
    code: 77096008,
    displayName: "انزواي اجتماعي (طرد شدن)",
    englishName: "Social isolation (rejection) (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 369,
    code: 276452005,
    displayName: "جرم دنداني",
    englishName: "Some dental plaque (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 370,
    code: 302228007,
    displayName: "اکيموز خود به خودي",
    englishName: "Spontaneous ecchymosis (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 371,
    code: 248596009,
    displayName: "خلط غيرطبيعي",
    englishName: "Sputum - symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 372,
    code: 161882006,
    displayName: "سفتي گردن",
    englishName: "Stiff neck (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 373,
    code: 51197009,
    displayName: "دل پيچه",
    englishName: "Stomach cramps (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 374,
    code: 298687002,
    displayName: "ازمون مثبت بلند کردن اندام تحتاني",
    englishName: "Straight leg raising reduced (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 375,
    code: 73595000,
    displayName: "استرس",
    englishName: "Stress (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 376,
    code: 70407001,
    displayName: "استريدور",
    englishName: "Stridor (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 377,
    code: 304594002,
    displayName: "قصد خودکشي",
    englishName: "Suicidal intent (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 378,
    code: 6471006,
    displayName: "افکار خودکشي",
    englishName: "Suicidal thoughts (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 379,
    code: 246923005,
    displayName: "فرورفتگي چشم ها",
    englishName: "Sunken eyes (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 380,
    code: 8381001,
    displayName: "فونتانل فرو رفته",
    englishName: "Sunken fontanelle (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 381,
    code: 162053006,
    displayName: "درد زير دل",
    englishName: "Suprapubic pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 382,
    code: 399122003,
    displayName: "اختلال بلع",
    englishName: "Swallowing problem (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 383,
    code: 299760001,
    displayName: "اختلال يا فقدان رفلکس بلع",
    englishName: "Swallowing reflex absent (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 384,
    code: 415690000,
    displayName: "تعريق",
    englishName: "Sweating (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 385,
    code: 300885006,
    displayName: "تورم پستان",
    englishName: "Swelling of breast (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 386,
    code: 193967004,
    displayName: "تورم پلک",
    englishName: "Swelling of eyelid (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 387,
    code: 300884005,
    displayName: "تورم در ناحيه تناسلي زنانه",
    englishName: "Swelling of female genital structure (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 388,
    code: 299322007,
    displayName: "تورم مفصل زانو",
    englishName: "Swelling of knee joint (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 389,
    code: 300882009,
    displayName: "تورم در ناحيه تناسلي مردانه",
    englishName: "Swelling of male genital structure (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 390,
    code: 271687003,
    displayName: "تورم بيش از حد اسکروتوم",
    englishName: "Swelling of scrotum (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 391,
    code: 277207000,
    displayName: "تورم ناحيه پشت گوش",
    englishName: "Swelling over mastoid (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 392,
    code: 60728008,
    displayName: "اتساع شکم",
    englishName: "Swollen abdomen (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 393,
    code: 267039000,
    displayName: "تورم قوزک پا",
    englishName: "Swollen ankle (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 394,
    code: 3424008,
    displayName: "تاکي کاردي",
    englishName: "Tachycardia (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 395,
    code: 271823003,
    displayName: "تاکي پنه ( تنفس تندتر از حد نرمال )",
    englishName: "Tachypnea (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 396,
    code: 300942003,
    displayName: "غده لنفاوي بزرگ و دردناک",
    englishName: "Tender lymph node (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 397,
    code: 277210007,
    displayName: "حساسيت، تورم و درد استخوان پشت گوش",
    englishName: "Tender mastoid (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 398,
    code: 277241008,
    displayName: "حساسيت صورت هنگام فشار روي سينوس پيشاني",
    englishName: "Tenderness over frontal sinus (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 399,
    code: 225875000,
    displayName: "فکر کردن به مرگ",
    englishName: "Thoughts about dying (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 400,
    code: 64661000,
    displayName: "نبض تند و ضعيف",
    englishName: "Thready pulse (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 401,
    code: 248269005,
    displayName: "خستگي زودرس در فعاليت",
    englishName: "Tired on least exertion (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 402,
    code: 110483000,
    displayName: "مصرف کننده دخانيات",
    englishName: "Tobacco user (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 403,
    code: 27355003,
    displayName: "درد دندان",
    englishName: "Toothache (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 404,
    code: 279044000,
    displayName: "سندرم درد کل بدن",
    englishName: "Total body pain syndrome (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 405,
    code: 26079004,
    displayName: "ترمور",
    englishName: "Tremor (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 406,
    code: 87866006,
    displayName: "تريسموس",
    englishName: "Trismus (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 407,
    code: 78349008,
    displayName: "خونريزي ناف",
    englishName: "Umbilical bleeding (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 408,
    code: 35745008,
    displayName: "ترشحات ناف",
    englishName: "Umbilical discharge (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 409,
    code: 60032008,
    displayName: "عدم توانايي در تمرکز",
    englishName: "Unable to concentrate (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 410,
    code: 288854000,
    displayName: "عدم توانايي نوشيدن",
    englishName: "Unable to drink (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 411,
    code: 288885009,
    displayName: "عدم توانايي در خوردن",
    englishName: "Unable to eat (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 412,
    code: 418107008,
    displayName: "عدم هوشياري",
    englishName: "Unconscious (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 413,
    code: 448765001,
    displayName: "کاهش وزن ناخواسته",
    englishName: "Unintentional weight loss (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 414,
    code: 249990003,
    displayName: "ناپايداري هنگام ايستادن",
    englishName: "Unsteady when standing (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 415,
    code: 22631008,
    displayName: "ناپايداري هنگام راه رفتن",
    englishName: "Unsteady when walking (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 416,
    code: 427797008,
    displayName: "تغيير ناگهاني رفتار",
    englishName: "Unusual change in behavior (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 417,
    code: 83132003,
    displayName: "درد بالاي شکم",
    englishName: "Upper abdominal pain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 418,
    code: 75088002,
    displayName: "تمايل فوري به ادرار کردن",
    englishName: "Urgent desire to urinate (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 419,
    code: 165232002,
    displayName: "بي اختياري ادرار",
    englishName: "Urinary incontinence (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 420,
    code: 39575007,
    displayName: "ادرار تيره",
    englishName: "Urine looks dark (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 421,
    code: 162135003,
    displayName: "ادرار کم رنگ",
    englishName: "Urine looks pale (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 422,
    code: 289700000,
    displayName: "وجود انقباضات رحمي",
    englishName: "Uterine contractions present (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 423,
    code: 289632007,
    displayName: "رحم با اندازه طبيعي",
    englishName: "Uterus normal size (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 424,
    code: 397940009,
    displayName: "کودک ازاري",
    englishName: "Victim of child abuse (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 425,
    code: 300361008,
    displayName: "استفراغ خوني",
    englishName: "Vomit contains blood (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 426,
    code: 249497008,
    displayName: "استفراغ",
    englishName: "Vomiting symptom (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 427,
    code: 225876004,
    displayName: "ارزوي مرگ",
    englishName: "Wanting to die (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 428,
    code: 420103007,
    displayName: "اشک ريزش",
    englishName: "Watery eye (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 429,
    code: 8943002,
    displayName: "افزايش وزن",
    englishName: "Weight gain (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 430,
    code: 89362005,
    displayName: "کاهش وزن",
    englishName: "Weight loss (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 431,
    code: 56018004,
    displayName: "خس خس سينه",
    englishName: "Wheezing (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 432,
    code: 60537006,
    displayName: "تنفس whooping",
    englishName: "Whooping respiration (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 433,
    code: 79015004,
    displayName: "نگراني",
    englishName: "Worried (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
  {
    id: 434,
    code: 248626009,
    displayName: "خميازه کشيدن",
    englishName: "Yawning (finding)",
    terminology: " SNOMEDCT",
    status: "1",
  },
];
export default complaints;
