const Expertise = [
  {
    specCode: "00187",
    specDesc: "بهداشت سالمندان",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00199",
    specDesc: "بيولوژي پزشکي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00181",
    specDesc: "دکتراي حرفه اي داروسازي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00182",
    specDesc: "دکتراي حرفه اي کايروپراکتيک",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00190",
    specDesc: "علوم بهداشتي در تغذيه",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00192",
    specDesc: "کارشناسي بينايي سنجي (اپتومتري)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00200",
    specDesc: "بهداشت خانواده",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00183",
    specDesc: "دکتراي تخصصي (Ph.D) فيزيوتراپي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00186",
    specDesc: "کارشناسي کاردرماني",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00189",
    specDesc: "تخصص فيزيکال مديسين و روماتولوژي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00191",
    specDesc: "دکتراي تخصصي (Ph.D) علوم پايه اعصاب",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00195",
    specDesc: "دکتراي حرفه اي علوم آزمايشگاهي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00184",
    specDesc: "کارشناسي شنوايي شناسي (اديولوژي)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00194",
    specDesc: "آسيب شناسي تشريحي و باليني",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00196",
    specDesc: "تخصص بهداشت عمومي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00198",
    specDesc: "آسيب شناسي باليني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00185",
    specDesc: "تخصص پزشکي ورزشي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00193",
    specDesc: "کارشناسي گفتاردرماني",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00197",
    specDesc: "فوق تخصص بيماريهاي متابوليک ارثي",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00201",
    specDesc: "تخصص آناتومي دندان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00202",
    specDesc: "دندان پزشک متخصص ايمپلنت دنداني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00203",
    specDesc: "تخصص دندانپزشکي کودکان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00204",
    specDesc: "تخصص مرتب سازي دندان (ارتودانتيکس)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00205",
    specDesc: "تخصص جراحي دهان، فک و صورت",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00206",
    specDesc: "تخصص جراحي لثه (پريودانتيکس)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00207",
    specDesc: "دندان پزشک متخصص بيماريهاي دهان و تشخيص",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00208",
    specDesc: "تخصص دندانپزشکي ترميمي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00209",
    specDesc: "تخصص درمان ريشه (اندودانتيکس)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00210",
    specDesc: "تخصص پروتزهاي دنداني (پروستودانتيکس)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00211",
    specDesc: "دندان پزشک متخصص پروتزهاي ثابت و اکلوژن",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00212",
    specDesc: "تخصص آسيب شناسي فک و دهان (پاتولوژي فک و دهان)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00213",
    specDesc: "تخصص بيولوژي دهان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00214",
    specDesc: "تخصص بهداشت خانواده",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00122",
    specDesc: "فوق تخصص بيماري هاي عفوني کودکان",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00123",
    specDesc: "فوق تخصص بيماري هاي مغز و اعصاب کودکان (نورولوژي کودکان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00124",
    specDesc: "تخصص تصوير برداري (راديولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00125",
    specDesc: "تخصص پرتودرماني (راديوتراپي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00126",
    specDesc: "پزشكي اجتماعي",
    specGRP: "2",
    docComment: null,
    status: "2",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00127",
    specDesc: "تخصص پزشکي هسته اي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00128",
    specDesc: "تخصص روانپزشکي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00129",
    specDesc: "فوق تخصص روانپزشکي-اطفال",
    specGRP: "8",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00130",
    specDesc: "تخصص طب کار",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00131",
    specDesc: "تخصص پزشکي فيزيکي و توانبخشي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00132",
    specDesc: "تخصص پزشکي قانوني (100)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00133",
    specDesc: "تخصص طب اورژانس",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00134",
    specDesc: "تخصص آسيب شناسي (پاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00135",
    specDesc: "تخصص جراحي عمومي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00136",
    specDesc: "فوق تخصص جراحي-اطفال",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00137",
    specDesc: "فوق تخصص جراحي قفسه صدري ( جراحي توراکس)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00138",
    specDesc: "فوق تخصص جراحي قلب و عروق",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00139",
    specDesc: "فوق تخصص جراحي-پلاستيک وترميمي",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00215",
    specDesc: "تخصص سالمندشناسي (ژرياتريک)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00140",
    specDesc: "تخصص جراحي استخوان و مفاصل (ارتوپدي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00141",
    specDesc: "فوق تخصص ارتوپدي-زانو",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00142",
    specDesc: "فوق تخصص ارتوپدي-دست",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00143",
    specDesc: "تخصص جراحي کليه، مجاري ادراري و تناسلي (اورولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00144",
    specDesc: "تخصص جراحي مغز و اعصاب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00145",
    specDesc: "تخصص چشم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00146",
    specDesc: "فوق تخصص چشم-شبكيه",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00147",
    specDesc: "فوق تخصص چشم-قرنيه",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00148",
    specDesc: "فوق تخصص چشم-استرانيسم",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00149",
    specDesc: "فوق تخصص چشم-نوروافتالمولوژيست",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00150",
    specDesc: "فوق تخصص چشم-اكونوپلاستيك",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00151",
    specDesc: "تخصص زنان و زايمان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00152",
    specDesc: "تخصص بيهوشي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00153",
    specDesc: "تخصص طب هوا فضا",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00154",
    specDesc: "دکتراي تخصصي (Ph.D) فيزيولوژي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00155",
    specDesc: "فارماكولوژي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00156",
    specDesc: "دکتراي تخصصي (Ph.D) ايمني شناسي (ايمونولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00157",
    specDesc: "دکتراي تخصصي (Ph.D) ميکروب شناسي آزمايشگاهي (ميکروبيولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00158",
    specDesc: "دکتراي تخصصي (Ph.D) قارچ شناسي آزمايشگاهي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00159",
    specDesc: "دکتراي تخصصي (Ph.D) انگل شناسي آزمايشگاهي ( پارازيتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00160",
    specDesc: "دکتراي تخصصي (Ph.D) علوم تشريحي (آناتومي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00161",
    specDesc: "دکتراي تخصصي (Ph.D) بيوشيمي آزمايشگاهي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00162",
    specDesc: "دکتراي تخصصي (Ph.D) سيتوژنتيک",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00163",
    specDesc: "دکتراي تخصصي (Ph.D) اپيدميولوژي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00164",
    specDesc: "کارشناسي علوم تغذيه",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00165",
    specDesc: "کارشناسي ارشد بهداشت مادر و کودک",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00166",
    specDesc: "آمار حياتي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00167",
    specDesc: "جنين شناسي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00168",
    specDesc: "دکتراي تخصصي (Ph.D) بافت شناسي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00169",
    specDesc: "اقتصاد درمان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00170",
    specDesc: "پزشكي نظامي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00171",
    specDesc: "دکتراي تخصصي (Ph.D) مديريت خدمات بهداشتي و درماني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00172",
    specDesc: "دکتراي حرفه اي دندانپزشکي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00173",
    specDesc: "دندانپزشك متخصص",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00174",
    specDesc: "کارشناسي مامايي",
    specGRP: "5",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00175",
    specDesc: "تخصص گوش، گلو، بيني و جراحي سر و گردن",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00176",
    specDesc: "تخصص پزشکي اجتماعي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "2",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00178",
    specDesc: "طب پيشگيري",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00179",
    specDesc: "دکتراي حرفه اي خون شناسي باليني (هماتولوژي باليني)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00100",
    specDesc: "دکتراي حرفه اي پزشکي (عمومي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00102",
    specDesc: "تخصص بيماري هاي داخلي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "2",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00103",
    specDesc: "فوق تخصص بيماري هاي کليه بزرگسالان (نفرولوژي بزرگسالان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00104",
    specDesc: "فوق تخصص بيماري هاي قلب و عروق",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00105",
    specDesc: "فوق تخصص بيماري هاي روماتولوژي",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00106",
    specDesc:
      "فوق تخصص بيماري هاي خون و سرطان بزرگسالان (هماتولوژي انکولوژي بزرگسالان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00107",
    specDesc: "فوق تخصص بيماري هاي غدد درون ريز و متابوليسم (اندوکرينولوژي)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00108",
    specDesc: "فوق تخصص بيماري هاي ريه",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "3",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00109",
    specDesc: "فوق تخصص بيماري هاي گوارش و کبد بزرگسالان",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00110",
    specDesc: "تخصص بيماري هاي قلب و عروق",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00111",
    specDesc: "تخصص بيماري هاي مغز و اعصاب (نورولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00112",
    specDesc: "تخصص بيماري هاي پوست (درماتولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00113",
    specDesc: "تخصص بيماري هاي عفوني و گرمسيري",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00114",
    specDesc: "تخصص بيماري هاي کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00115",
    specDesc: "فوق تخصص بيماري هاي کليه کودکان (نفرولوژي کودکان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00116",
    specDesc: "فوق تخصص بيماري هاي قلب کودکان",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00117",
    specDesc: "فوق تخصص اطفال-ايمونولوژي",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00118",
    specDesc:
      "فوق تخصص بيماري هاي خون و سرطان کودکان (هماتولوژي انکولوژي کودکان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00119",
    specDesc:
      "فوق تخصص بيماري هاي غدد درون ريز و متابوليسم کودکان (اندوکرينولوژي کودکان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00120",
    specDesc: "فوق تخصص طب نوزادي و پيرامون تولد",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00121",
    specDesc: "فوق تخصص بيماري هاي گوارش کودکان",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00177",
    specDesc: "تخصص پزشکي خانواده",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00180",
    specDesc: "فوق تخصص بخشهاي ويژه",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13900101",
    typeSpec: "3",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00300",
    specDesc: "فلوشيپ انکولوژي",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00301",
    specDesc:
      "فلوشيپ بيماري هاي خون و سرطان بزرگسالان (هماتولوژي انکولوژي بزرگسالان)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00302",
    specDesc: "فوق تخصص سرطان شناسي (انکولوژي)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00303",
    specDesc: "فلوشيپ بيماري هاي ريه",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "3",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00304",
    specDesc: "تخصص الکتروفيزيولوژي باليني قلب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00305",
    specDesc: "فلوشيپ اکوکارديوگرافي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00306",
    specDesc: "فلوشيپ نارسايي قلب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00307",
    specDesc:
      "فلوشيپ اقدامات مداخله اي قلب و عروق بزرگسالان (اينترونشن قلب بزرگسالان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00308",
    specDesc: "فلوشيپ اينترونشنال کارديولوژي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00309",
    specDesc: "فلوشيپ پيس ميکر و اينترونشنال الکتروفيزيولوژي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00310",
    specDesc: "فلوشيپ الکتروفيزيولوژي باليني قلب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00311",
    specDesc: "فلوشيپ الکتروفيزيولوژي و پيس ميکر",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00312",
    specDesc: "فلوشيپ بيماري هاي قلب و عروق",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00313",
    specDesc:
      "فوق تخصص اقدامات مداخله اي قلب و عروق بزرگسالان (اينترونشن قلب بزرگسالان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00314",
    specDesc: "فلوشيپ بيماريهاي مادرزادي قلب و عروق در بالغين",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00315",
    specDesc: "فلوشيپ مولتيپل اسکلروزيس (ام اس)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00316",
    specDesc: "فلوشيپ صرع",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00317",
    specDesc: "فلوشيپ فيزيولوژي اعصاب (نوروفيزيولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00318",
    specDesc: "فلوشيپ اختلالات حرکتي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00319",
    specDesc: "فلوشيپ استروتاکسي و فانکشنال مغز و اعصاب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00320",
    specDesc: "فلوشيپ آسيب شناسي اعصاب (نوروپاتولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00321",
    specDesc: "فلوشيپ استروک",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00322",
    specDesc: "فلوشيپ اقدامات مداخله اي اعصاب (نورواينترونشن)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00323",
    specDesc: "فلوشيپ سکته مغزي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00324",
    specDesc: "فلوشيپ عصبي عضلاني (نوروماسکولار)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00325",
    specDesc: "فلوشيپ نخاع",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00326",
    specDesc: "فوق تخصص الکتروميوگرافي و هدايت عصبي محيطي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00327",
    specDesc: "فوق تخصص بيماري هاي مغز و اعصاب (نورولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00328",
    specDesc: "فلوشيپ زيبايي پوست و ليزر",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00329",
    specDesc: "فلوشيپ جراحي پوست",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00330",
    specDesc: "فلوشيپ بيماري ايدز باليني (HIV/AIDS)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00331",
    specDesc: "فلوشيپ بيماري هاي عفوني در بيماران مبتلا به نقص ايمني",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00332",
    specDesc: "فلوشيپ اورژانس کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00333",
    specDesc: "فلوشيپ بيماري هاي ريه کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00334",
    specDesc: "فلوشيپ بيماري هاي روماتولوژي کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00335",
    specDesc: "فوق تخصص بيماري هاي روماتولوژي کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00336",
    specDesc: "فوق تخصص بيماري هاي ريه کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00337",
    specDesc: "فلوشيپ بيماري هاي مغز و اعصاب کودکان (نورولوژي کودکان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00338",
    specDesc: "تخصص تصويربرداري اعصاب (نوروراديولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00339",
    specDesc: "فلوشيپ تصويربرداري اعصاب (نوروراديولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00340",
    specDesc: "فلوشيپ تصويربرداري مداخله اي (اينترونشنال راديولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00341",
    specDesc: "فلوشيپ تصويربرداري مداخله اي اعصاب (اينترونشنال نوروراديولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00342",
    specDesc: "فلوشيپ سي تي اسکن و ام آر آي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00343",
    specDesc: "فوق تخصص تصويربرداري اعصاب (نوروراديولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00477",
    specDesc: "تخصص تصويربرداري دهان، فک و صورت (راديولوژي دهان، فک و صورت)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00344",
    specDesc: "فلوشيپ پرتودرماني (راديوتراپي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00345",
    specDesc: "فلوشيپ انکولوژي هسته اي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00346",
    specDesc: "تخصص روانپزشکي کودک و نوجوان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00347",
    specDesc: "فلوشيپ طب خواب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00348",
    specDesc: "فلوشيپ طب روان تني ( سايکوسوماتيک)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00349",
    specDesc: "فلوشيپ درمان اعتياد",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00350",
    specDesc: "فلوشيپ روانپزشکي کودک و نوجوان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00351",
    specDesc: "فوق تخصص روانپزشکي کودک و نوجوان",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00260",
    specDesc: "فلوشيپ پزشکي فيزيکي و توانبخشي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00352",
    specDesc: "فلوشيپ سم شناسي باليني ",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00353",
    specDesc: "تخصص سم شناسي عمومي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00354",
    specDesc: "دکتراي حرفه اي آسيب شناسي (پاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00355",
    specDesc: "فلوشيپ آسيب شناسي چشم (افتالموپاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00356",
    specDesc: "فلوشيپ آسيب شناسي خون (هماتوپاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00357",
    specDesc: "فلوشيپ آسيب شناسي سلولي (سيتوپاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00358",
    specDesc: "فلوشيپ آسيب شناسي کليه (نفروپاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00359",
    specDesc: "فلوشيپ آسيب شناسي کودکان (پاتولوژي کودکان)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00360",
    specDesc: "فلوشيپ آسيب شناسي (پاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00361",
    specDesc: "فلوشيپ آسيب شناسي پوست (درماتوپاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00362",
    specDesc: "فلوشيپ مولکولارژنوميک پاتولوزي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00363",
    specDesc: "فوق تخصص آسيب شناسي خون (هماتوپاتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00364",
    specDesc: "فوق تخصص آسيب شناسي کودکان (پاتولوژي کودکان)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00365",
    specDesc: "فلوشيپ مولکولار پاتولوژي و سيتوژنتيک",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00366",
    specDesc: "تخصص جراحي سوانح و حوادث",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00367",
    specDesc: "فلوشيپ جراحي پا و مچ پا",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00368",
    specDesc: "فلوشيپ جراحي پستان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00369",
    specDesc: "فلوشيپ جراحي ترميمي اندام تحتاني و سرطان شناسي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00370",
    specDesc: "فلوشيپ جراحي تومورهاي سيستم اسکلتي و عضلاني",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00371",
    specDesc: "فلوشيپ جراحي دست",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00372",
    specDesc: "فلوشيپ جراحي روده بزرگ (جراحي کولورکتال)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00373",
    specDesc: "فلوشيپ جراحي زيبايي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00374",
    specDesc: "فلوشيپ جراحي سر و گردن",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00375",
    specDesc: "فلوشيپ جراحي سرطان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00376",
    specDesc: "فلوشيپ جراحي عروق",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00377",
    specDesc: "فلوشيپ جراحي عروق و تروما",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00378",
    specDesc: "فلوشيپ تروما در جراحي عمومي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00379",
    specDesc: "فلوشيپ جراحي عمومي درون بين (اندوسکوپي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00380",
    specDesc: "فلوشيپ جراحي لگن",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00381",
    specDesc: "فلوشيپ پيوند کبد",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00382",
    specDesc: "فلوشيپ پيوند کليه",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00383",
    specDesc: "فوق تخصص جراحي عروق",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00384",
    specDesc: "فوق تخصص جراحي عروق و تروما",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00385",
    specDesc: "فلوشيپ Bariatric",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00386",
    specDesc: "فلوشيپ جراحي کم تهاجمي پيشرفته و چاقي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00387",
    specDesc: "فلوشيپ جراحي پيوندکبد",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00388",
    specDesc: "فوق تخصص جراحي عروق، پيوند کليه و کبد",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00389",
    specDesc: "فلوشيپ جراحي عروق، پيوند کليه و کبد",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00390",
    specDesc: "فوق تخصص جراحي کودکان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00391",
    specDesc:
      "فوق تخصص جراحي کليه، مجاري ادراري و تناسلي کودکان (اورولوژي کودکان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00392",
    specDesc: "تخصص جراحي قلب و عروق",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00393",
    specDesc: "فلوشيپ جراحي بيماري هاي مادرزادي قلب",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00394",
    specDesc: "فلوشيپ جراحي پلاستيک چشم و انحراف چشم (اکولوپلاستي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00395",
    specDesc: "فلوشيپ جراحي پلاستيک و ترميمي چشم (اکولوپلاستي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00396",
    specDesc: "فلوشيپ جراحي پلاستيک، ترميمي و سوختگي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00397",
    specDesc: "فلوشيپ جراحي پلاستيک و ترميمي فک و صورت",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00398",
    specDesc: "فلوشيپ سوختگي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00399",
    specDesc: "فوق تخصص جراحي پلاستيک، ترميمي و سوختگي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00400",
    specDesc: "فوق تخصص جراحي پلاستيک و ترميمي چشم (اکولوپلاستي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00401",
    specDesc: "فلوشيپ جراحي آرتروسکوپي و طب ورزشي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00402",
    specDesc: "فلوشيپ جراحي آرتروسکوپي زانو و هيپ",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00403",
    specDesc: "فلوشيپ جراحي استخوان و مفاصل کودکان (ارتوپدي کودکان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00404",
    specDesc: "فلوشيپ جراحي زانو",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00405",
    specDesc: "فلوشيپ جراحي ستون فقرات",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00406",
    specDesc: "فلوشيپ جراحي شانه",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00407",
    specDesc: "فلوشيپ آرتروپلاستي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00408",
    specDesc: "فوق تخصص جراحي زانو",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00545",
    specDesc: "فوق تخصص جراحي دست",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00410",
    specDesc: "فوق تخصص جراحي تعويض مفصل ران و اندام هاي تحتاني",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00411",
    specDesc: "فوق تخصص سرطان دستگاه ادراري و تناسلي (اروانکولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00412",
    specDesc:
      "فلوشيپ جراحي درون بين کليه، مجاري ادراري و تناسلي (اندويورولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00413",
    specDesc: "فلوشيپ سرطان دستگاه ادراري و تناسلي (اروانکولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00414",
    specDesc:
      "فلوشيپ جراحي کليه، مجاري ادراري و تناسلي کودکان (اورولوژي کودکان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00415",
    specDesc: "فلوشيپ جراحي کليه، مجاري ادراري و تناسلي زنان (اورولوژي زنان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00416",
    specDesc: "فوق تخصص جراحي کليه، مجاري ادراري و تناسلي (اورولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00417",
    specDesc: "فلوشيپ بيماري هاي کليه بزرگسالان (نفرولوژي بزرگسالان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00418",
    specDesc: "فلوشيپ جراحي کليه، مجاري ادراري و تناسلي (اورولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00419",
    specDesc: "فلوشيپ جراحي قاعده جمجمه",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00420",
    specDesc: "فلوشيپ چشم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00421",
    specDesc: "فلوشيپ چشم پزشکي کودکان و انحراف چشم (استرابيسم)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00422",
    specDesc: "فلوشيپ استرابيسم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00423",
    specDesc: "فلوشيپ قرنيه و خارج چشمي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00424",
    specDesc: "فلوشيپ گلوکوم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00425",
    specDesc: "فلوشيپ ويتره و رتين",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00426",
    specDesc: "فلوشيپ يووئيت و بيماري هاي التهابي چشم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00427",
    specDesc: "فلوشيپ بيماري هاي سطح چشم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00428",
    specDesc: "فلوشيپ سرطان چشم",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00429",
    specDesc: "فلوشيپ شبکيه",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00430",
    specDesc: "فوق تخصص سرطان شناسي زنان (انکولوژي زنان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00431",
    specDesc: "فلوشيپ زنان و زايمان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00432",
    specDesc: "فلوشيپ سرطان شناسي زنان (انکولوژي زنان)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00433",
    specDesc: "فلوشيپ سونوگرافي زنان و زايمان ",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00434",
    specDesc: "فلوشيپ آي وي اف",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00435",
    specDesc: "فلوشيپ نازايي و آي وي اف",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00436",
    specDesc: "فلوشيپ طب مادر و جنين (پريناتولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00437",
    specDesc: "فلوشيپ لاپاراسکوپي و آي وي اف",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00438",
    specDesc: "فلوشيپ لاپاراسکوپي و هيستروسکوپي زنان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00439",
    specDesc: "فلوشيپ اختلالات کف لگن در زنان",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00440",
    specDesc: "فوق تخصص نازايي و آي وي اف",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00441",
    specDesc: "فوق تخصص لاپاراسکوپي و آي وي اف",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00442",
    specDesc: "تخصص بيهوشي کودکان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00443",
    specDesc: "فلوشيپ درد",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00444",
    specDesc: "فلوشيپ طب تسکيني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00445",
    specDesc: "فلوشيپ مراقبت هاي ويژه (آي سي يو)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00446",
    specDesc: "فلوشيپ بيهوشي کودکان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00447",
    specDesc: "فلوشيپ بيهوشي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00448",
    specDesc: "فلوشيپ رانيماسيون",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00449",
    specDesc: "فلوشيپ بيهوشي قلب",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00450",
    specDesc: "فلوشيپ بيهوشي مغز و اعصاب",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00451",
    specDesc: "فلوشيپ مراقبت هاي ويژه کودکان",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00452",
    specDesc: "فوق تخصص بيهوشي قلب",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00453",
    specDesc: "کارشناسي فيزيولوژي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00530",
    specDesc: "دکتراي تخصصي (Ph.D) ايمني شناسي و خون شناسي (ايمونوهماتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00454",
    specDesc: "کارشناسي ارشد ايمني شناسي آزمايشگاهي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00455",
    specDesc: "دکتراي تخصصي (Ph.D) ايمني شناسي آزمايشگاهي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00456",
    specDesc: "دکتراي تخصصي (Ph.D) ايمني شناسي باليني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00457",
    specDesc: "کارشناسي ارشد ميکروب شناسي آزمايشگاهي (ميکروبيولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00458",
    specDesc: "کارشناسي ويروس شناسي آزمايشگاهي (ويرولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00459",
    specDesc: "کارشناسي ارشد ويروس شناسي آزمايشگاهي (ويرولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00460",
    specDesc: "دکتراي تخصصي (Ph.D) ويروس شناسي آزمايشگاهي (ويرولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00461",
    specDesc: "دکتراي تخصصي (Ph.D) باکتري شناسي آزمايشگاهي (باکتريولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00542",
    specDesc: "کارشناسي ارشد انگل شناسي آزمايشگاهي ( پارازيتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00543",
    specDesc:
      "دکتراي تخصصي (Ph.D) ايمني شناسي و انگل شناسي (ايمونوپارازيتولوژي)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00462",
    specDesc: "کارشناسي ارشد بيوشيمي آزمايشگاهي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00463",
    specDesc: "کارشناسي ارشد بيوشيمي باليني ",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00464",
    specDesc: "دکتراي تخصصي (Ph.D) بيوشيمي باليني ",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00465",
    specDesc: "دکتراي تخصصي (Ph.D) ژنتيک انساني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00466",
    specDesc: "دکتراي تخصصي (Ph.D) ژنتيک انساني با گرايش مولکولي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00467",
    specDesc: "دکتراي تخصصي (Ph.D) ژنتيک پزشکي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00468",
    specDesc: "دکتراي تخصصي (Ph.D) ژنتيک پزشکي با گرايش ژنتيک مولکولي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00469",
    specDesc: "دکتراي تخصصي (Ph.D) ژنتيک مولکولي انساني ",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00470",
    specDesc: "دکتراي تخصصي (Ph.D) ژنتيک مولکولي باليني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00471",
    specDesc: "دکتراي تخصصي (Ph.D) سيتوژنتيک پزشکي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00472",
    specDesc: "فلوشيپ سيتوژنتيک",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00473",
    specDesc: "فوق تخصص ژنتيک پزشکي",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00474",
    specDesc: "کارشناسي ارشد علوم تغذيه",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00475",
    specDesc: "دکتراي تخصصي (Ph.D) علوم تغذيه",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00476",
    specDesc: "تخصص علوم تغذيه",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00478",
    specDesc: "فلوشيپ دندانپزشکي بيمارستاني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00479",
    specDesc: "کارشناسي ارشد آموزش مامايي",
    specGRP: "5",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00480",
    specDesc: "کارشناسي ارشد مامايي",
    specGRP: "5",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00481",
    specDesc: "فلوشيپ جراحي بيني و سينوس (رينولوژي)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00482",
    specDesc: "فلوشيپ گوش، گلو، بيني و جراحي سر و گردن",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00483",
    specDesc: "فلوشيپ اتولوژي - نورواتولوژي",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00484",
    specDesc: "دکتراي تخصصي (Ph.D) پزشکي اجتماعي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00485",
    specDesc: "دکتراي حرفه اي پزشکي خانواده",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00487",
    specDesc: "دکتراي تخصصي (Ph.D) خون شناسي باليني (هماتولوژي باليني)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00486",
    specDesc: "دکتراي تخصصي (Ph.D) هماتولوژي آزمايشگاهي و بانک خون ",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00488",
    specDesc:
      "کارشناسي ارشد خون شناسي آزمايشگاهي و بانک خون (هماتولوژي آزمايشگاهي و بانک خون)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00489",
    specDesc: "کارشناسي داروسازي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00490",
    specDesc: "کارشناسي ارشد داروسازي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00491",
    specDesc: "دکتراي تخصصي (Ph.D) داروسازي صنعتي (فارماسيوتيکس)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00492",
    specDesc: "دکتراي تخصصي (Ph.D) داروشناسي (فارماکولوژي)  ",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00493",
    specDesc: "دکتراي تخصصي (Ph.D) شيمي دارويي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00494",
    specDesc: "دکتراي تخصصي (Ph.D) فارماکوگنوزي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00495",
    specDesc: "دکتراي تخصصي (Ph.D) فارماسيوتيکس (فناوري دارويي)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00525",
    specDesc: "فلوشيپ جراحي لثه و کاشت دندان (پريوايمپلنت)",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00526",
    specDesc: "دکتراي تخصصي (Ph.D) کاشت دندان (ايمپلنت)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00527",
    specDesc: "فلوشيپ ارتوسرجري",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00531",
    specDesc: "فلوشيپ کاشت دندان (ايمپلنت)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00528",
    specDesc: "دکتراي تخصصي (Ph.D) سلامت دهان و دندانپزشکي اجتماعي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00544",
    specDesc: "تخصص بيماري هاي دهان، فک و صورت",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00529",
    specDesc: "دکتراي تخصصي (Ph.D) بهداشت عمومي دندانپزشکي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00532",
    specDesc: "دکتراي تخصصي (Ph.D) بهداشت خانواده",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00533",
    specDesc: "دکتراي تخصصي (Ph.D) روانشناسي باليني",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00534",
    specDesc: "فلوشيپ بيماريهاي متابوليک استخوان",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00535",
    specDesc: "تخصص آلرژي و ايمني شناسي باليني (آلرژي و ايمونولوژي باليني)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00536",
    specDesc: "فلوشيپ آلرژي و ايمني شناسي باليني (آلرژي و ايمونولوژي باليني)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00537",
    specDesc: "فلوشيپ ايمني شناسي باليني",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00538",
    specDesc: "فوق تخصص آلرژي و ايمني شناسي باليني (آلرژي و ايمونولوژي باليني)",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00539",
    specDesc: "فوق تخصص ايمني شناسي باليني",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00540",
    specDesc: "فلوشيپ سالمندشناسي (ژرياتريک)",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00541",
    specDesc: "دکتراي تخصصي (Ph.D) سالمندشناسي (ژرياتريک)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00546",
    specDesc: "فوق تخصص گوش، گلو، بيني و جراحي سر و گردن",
    specGRP: "2",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: "1",
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00547",
    specDesc: "فلوشيپ جراحي پلاستيک صورت",
    specGRP: "3",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00548",
    specDesc: "دکتراي تخصصي (Ph.D) طب سنتي ايراني",
    specGRP: "1",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00496",
    specDesc: "تخصص داروسازي باليني (کلينيکال فارماسي)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00497",
    specDesc: "کارشناسي ارشد داروشناسي (فارماکولوژي)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00498",
    specDesc: "کارشناسي ارشد فارماکوگنوزي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00499",
    specDesc: "کارشناسي ارشد فارماسيوتيکس (فناوري دارويي)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00500",
    specDesc: "دکتراي تخصصي (Ph.D) داروسازي باليني (کلينيکال فارماسي)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00501",
    specDesc: "دکتراي تخصصي (Ph.D) سم شناسي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00502",
    specDesc: "دکتراي تخصصي (Ph.D) سم شناسي عمومي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00503",
    specDesc: "دکتراي حرفه اي داروشناسي (فارماکولوژي)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00504",
    specDesc: "تخصص فارماکوگنوزي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00505",
    specDesc: "تخصص فارماسيوتيکس (فناوري دارويي)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00506",
    specDesc: "کارشناسي فيزيوتراپي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00507",
    specDesc: "کارشناسي ارشد فيزيوتراپي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00508",
    specDesc: "کارشناسي ارشد شنوايي شناسي (اديولوژي)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00509",
    specDesc: "دکتراي تخصصي (Ph.D) شنوايي شناسي (اديولوژي)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00510",
    specDesc: "دکتراي تخصصي (Ph.D) پزشکي ورزشي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00511",
    specDesc: "کارشناسي ارشد کاردرماني",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00512",
    specDesc: "دکتراي تخصصي (Ph.D) کاردرماني",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00513",
    specDesc: "دکتراي تخصصي (Ph.D) علوم اعصاب",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00514",
    specDesc: "کارشناسي ارشد بينايي سنجي (اپتومتري)",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00515",
    specDesc: "دکتراي تخصصي (Ph.D) بينايي سنجي (اپتومتري)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00516",
    specDesc: "کارشناسي ارشد گفتاردرماني",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00517",
    specDesc: "دکتراي تخصصي (Ph.D) گفتاردرماني",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00518",
    specDesc: "کارشناسي علوم آزمايشگاهي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00519",
    specDesc:
      "دکتراي تخصصي (Ph.D) خون شناسي آزمايشگاهي و بانک خون (هماتولوژي آزمايشگاهي و بانک خون)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00520",
    specDesc: "دکتراي تخصصي (Ph.D) علوم آزمايشگاهي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00521",
    specDesc: "تخصص علوم آزمايشگاهي",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00522",
    specDesc: "فوق تخصص خون شناسي باليني (هماتولوژي باليني)",
    specGRP: "6",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00523",
    specDesc: "کارشناسي ارشد بهداشت عمومي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00524",
    specDesc: "کارشناسي بهداشت عمومي",
    specGRP: "7",
    docComment: null,
    status: "1",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00549",
    specDesc: "--------------",
    specGRP: "7",
    docComment: null,
    status: "2",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
  {
    specCode: "00550",
    specDesc: "--------------------",
    specGRP: "2",
    docComment: null,
    status: "2",
    statusstDate: "13980124",
    typeSpec: null,
    maxNormal: null,
    maxSpecial: null,
  },
];
export default Expertise;
